// Code generated by mapdb-codegen. DO NOT EDIT.

use std::sync::RwLock;

use super::bool_array_deque::BoolArrayDeque;

/// Thread-safe wrapper around [`BoolArrayDeque`].
#[derive(Debug, Default)]
pub struct SynchronizedBoolArrayDeque {
    inner: RwLock<BoolArrayDeque>,
}

impl SynchronizedBoolArrayDeque {
    pub fn new() -> Self {
        SynchronizedBoolArrayDeque {
            inner: RwLock::new(BoolArrayDeque::new()),
        }
    }

    pub fn of(values: &[bool]) -> Self {
        SynchronizedBoolArrayDeque {
            inner: RwLock::new(BoolArrayDeque::of(values)),
        }
    }

    pub fn add_first(&self, value: bool) {
        self.inner.write().unwrap().add_first(value);
    }

    pub fn add_last(&self, value: bool) {
        self.inner.write().unwrap().add_last(value);
    }

    pub fn remove_first(&self) -> Option<bool> {
        self.inner.write().unwrap().remove_first()
    }

    pub fn remove_last(&self) -> Option<bool> {
        self.inner.write().unwrap().remove_last()
    }

    pub fn peek_first(&self) -> Option<bool> {
        self.inner.read().unwrap().peek_first()
    }

    pub fn peek_last(&self) -> Option<bool> {
        self.inner.read().unwrap().peek_last()
    }

    pub fn contains(&self, value: bool) -> bool {
        self.inner.read().unwrap().contains(value)
    }

    pub fn len(&self) -> usize {
        self.inner.read().unwrap().len()
    }
    pub fn is_empty(&self) -> bool {
        self.inner.read().unwrap().is_empty()
    }
    pub fn clear(&self) {
        self.inner.write().unwrap().clear();
    }

    pub fn to_vec(&self) -> Vec<bool> {
        self.inner.read().unwrap().to_vec()
    }

    pub fn for_each(&self, f: impl FnMut(bool)) {
        self.inner.read().unwrap().for_each(f);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;
    use std::thread;

    #[test]
    fn test_basic_ops() {
        let d = SynchronizedBoolArrayDeque::new();
        assert!(d.is_empty());
        d.add_last(true);
        d.add_last(false);
        d.add_first(true);
        assert_eq!(d.len(), 3);
        assert_eq!(d.peek_first(), Some(true));
        assert_eq!(d.peek_last(), Some(false));
        assert_eq!(d.remove_first(), Some(true));
        assert_eq!(d.remove_last(), Some(false));
        assert!(d.contains(true));
        d.clear();
        assert!(d.is_empty());
    }

    #[test]
    fn test_to_vec_and_for_each() {
        let d = SynchronizedBoolArrayDeque::of(&[true, false, true]);
        assert_eq!(d.to_vec().len(), 3);
        let mut count = 0usize;
        d.for_each(|_| count += 1);
        assert_eq!(count, 3);
    }

    #[test]
    fn test_concurrent() {
        let d = Arc::new(SynchronizedBoolArrayDeque::new());
        let mut handles = Vec::new();
        for _ in 0..4 {
            let c = Arc::clone(&d);
            handles.push(thread::spawn(move || {
                for _ in 0..100 {
                    c.add_last(true);
                }
            }));
        }
        for h in handles {
            h.join().unwrap();
        }
        assert_eq!(d.len(), 400);
    }
}
