// Code generated by mapdb-codegen. DO NOT EDIT.

use std::sync::RwLock;

use super::i32_array_deque::I32ArrayDeque;

/// Thread-safe wrapper around [`I32ArrayDeque`].
#[derive(Debug, Default)]
pub struct SynchronizedI32ArrayDeque {
    inner: RwLock<I32ArrayDeque>,
}

impl SynchronizedI32ArrayDeque {
    pub fn new() -> Self {
        SynchronizedI32ArrayDeque {
            inner: RwLock::new(I32ArrayDeque::new()),
        }
    }

    pub fn of(values: &[i32]) -> Self {
        SynchronizedI32ArrayDeque {
            inner: RwLock::new(I32ArrayDeque::of(values)),
        }
    }

    pub fn add_first(&self, value: i32) {
        self.inner.write().unwrap().add_first(value);
    }

    pub fn add_last(&self, value: i32) {
        self.inner.write().unwrap().add_last(value);
    }

    pub fn remove_first(&self) -> Option<i32> {
        self.inner.write().unwrap().remove_first()
    }

    pub fn remove_last(&self) -> Option<i32> {
        self.inner.write().unwrap().remove_last()
    }

    pub fn peek_first(&self) -> Option<i32> {
        self.inner.read().unwrap().peek_first()
    }

    pub fn peek_last(&self) -> Option<i32> {
        self.inner.read().unwrap().peek_last()
    }

    pub fn contains(&self, value: i32) -> bool {
        self.inner.read().unwrap().contains(value)
    }

    pub fn len(&self) -> usize {
        self.inner.read().unwrap().len()
    }
    pub fn is_empty(&self) -> bool {
        self.inner.read().unwrap().is_empty()
    }
    pub fn clear(&self) {
        self.inner.write().unwrap().clear();
    }

    pub fn to_vec(&self) -> Vec<i32> {
        self.inner.read().unwrap().to_vec()
    }

    pub fn for_each(&self, f: impl FnMut(i32)) {
        self.inner.read().unwrap().for_each(f);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;
    use std::thread;

    #[test]
    fn test_basic_ops() {
        let d = SynchronizedI32ArrayDeque::new();
        assert!(d.is_empty());
        d.add_last(1);
        d.add_last(2);
        d.add_first(3);
        assert_eq!(d.len(), 3);
        assert_eq!(d.peek_first(), Some(3));
        assert_eq!(d.peek_last(), Some(2));
        assert_eq!(d.remove_first(), Some(3));
        assert_eq!(d.remove_last(), Some(2));
        assert!(d.contains(1));
        d.clear();
        assert!(d.is_empty());
    }

    #[test]
    fn test_to_vec_and_for_each() {
        let d = SynchronizedI32ArrayDeque::of(&[1, 2, 3]);
        assert_eq!(d.to_vec().len(), 3);
        let mut count = 0usize;
        d.for_each(|_| count += 1);
        assert_eq!(count, 3);
    }

    #[test]
    fn test_concurrent() {
        let d = Arc::new(SynchronizedI32ArrayDeque::new());
        let mut handles = Vec::new();
        for _ in 0..4 {
            let c = Arc::clone(&d);
            handles.push(thread::spawn(move || {
                for _ in 0..100 {
                    c.add_last(1);
                }
            }));
        }
        for h in handles {
            h.join().unwrap();
        }
        assert_eq!(d.len(), 400);
    }
}
