// Code generated by mapdb-codegen. DO NOT EDIT.

use crate::hash_table::OpenHashSet;
use std::fmt;

/// Hash set of unique `char` values.
/// Open-addressing with linear probing and Robin Hood backward-shift deletion.
#[derive(Debug, Clone)]
pub struct CharHashSet {
    inner: OpenHashSet<char>,
}

impl CharHashSet {
    pub fn new() -> Self {
        CharHashSet {
            inner: OpenHashSet::new(),
        }
    }

    pub fn of(values: &[char]) -> Self {
        let mut s = Self::new();
        for &v in values {
            s.add(v);
        }
        s
    }

    /// Adds a value. Returns true if it was not already present.
    pub fn add(&mut self, value: char) -> bool {
        self.inner.add(value)
    }

    /// Removes a value. Returns true if it was present.
    pub fn remove(&mut self, value: char) -> bool {
        self.inner.remove(value)
    }

    pub fn contains(&self, value: char) -> bool {
        self.inner.contains(value)
    }

    pub fn len(&self) -> usize {
        self.inner.len()
    }

    pub fn is_empty(&self) -> bool {
        self.inner.is_empty()
    }

    pub fn clear(&mut self) {
        self.inner.clear();
    }

    /// Ensures the set can accept `additional` more entries without a
    /// rehash. Returns `TryReserveError` on allocator failure. See
    /// `docs/rust/error-handling.md`.
    pub fn try_reserve(
        &mut self,
        additional: usize,
    ) -> Result<(), std::collections::TryReserveError> {
        self.inner.try_reserve(additional)
    }

    pub fn iter(&self) -> impl Iterator<Item = char> + '_ {
        self.inner.iter()
    }

    pub fn for_each(&self, mut f: impl FnMut(char)) {
        for v in self.iter() {
            f(v);
        }
    }

    pub fn select(&self, predicate: impl Fn(char) -> bool) -> Self {
        let mut result = Self::new();
        for v in self.iter() {
            if predicate(v) {
                result.add(v);
            }
        }
        result
    }

    pub fn reject(&self, predicate: impl Fn(char) -> bool) -> Self {
        let mut result = Self::new();
        for v in self.iter() {
            if !predicate(v) {
                result.add(v);
            }
        }
        result
    }

    pub fn detect(&self, predicate: impl Fn(char) -> bool) -> Option<char> {
        self.iter().find(|&v| predicate(v))
    }

    pub fn any_satisfy(&self, predicate: impl Fn(char) -> bool) -> bool {
        self.iter().any(predicate)
    }

    pub fn all_satisfy(&self, predicate: impl Fn(char) -> bool) -> bool {
        self.iter().all(predicate)
    }

    pub fn none_satisfy(&self, predicate: impl Fn(char) -> bool) -> bool {
        !self.iter().any(predicate)
    }

    pub fn union(&self, other: &Self) -> Self {
        let mut result = self.clone();
        for v in other.iter() {
            result.add(v);
        }
        result
    }

    pub fn intersect(&self, other: &Self) -> Self {
        let mut result = Self::new();
        for v in self.iter() {
            if other.contains(v) {
                result.add(v);
            }
        }
        result
    }

    pub fn difference(&self, other: &Self) -> Self {
        let mut result = Self::new();
        for v in self.iter() {
            if !other.contains(v) {
                result.add(v);
            }
        }
        result
    }

    pub fn symmetric_difference(&self, other: &Self) -> Self {
        let mut result = Self::new();
        for v in self.iter() {
            if !other.contains(v) {
                result.add(v);
            }
        }
        for v in other.iter() {
            if !self.contains(v) {
                result.add(v);
            }
        }
        result
    }

    pub fn to_vec(&self) -> Vec<char> {
        self.iter().collect()
    }

    pub fn with(mut self, value: char) -> Self {
        self.add(value);
        self
    }
    pub fn without(mut self, value: char) -> Self {
        self.remove(value);
        self
    }
}

impl Default for CharHashSet {
    fn default() -> Self {
        Self::new()
    }
}

impl PartialEq for CharHashSet {
    fn eq(&self, other: &Self) -> bool {
        if self.len() != other.len() {
            return false;
        }
        self.iter().all(|v| other.contains(v))
    }
}

impl Eq for CharHashSet {}

impl fmt::Display for CharHashSet {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{{")?;
        let mut first = true;
        for v in self.iter() {
            if !first {
                write!(f, ", ")?;
            }
            write!(f, "{}", v)?;
            first = false;
        }
        write!(f, "}}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_add_contains() {
        let mut s = CharHashSet::new();
        s.add('a');
        s.add('b');
        s.add('c');
        assert_eq!(s.len(), 3);
        assert!(s.contains('b'));
        assert!(!s.contains('z'));
    }

    #[test]
    fn test_add_duplicate() {
        let mut s = CharHashSet::new();
        assert!(s.add('a'));
        assert!(!s.add('a'));
        assert_eq!(s.len(), 1);
    }

    #[test]
    fn test_remove() {
        let mut s = CharHashSet::of(&['a', 'b', 'c']);
        assert!(s.remove('b'));
        assert!(!s.contains('b'));
        assert!(!s.remove('z'));
    }

    #[test]
    fn test_clear() {
        let mut s = CharHashSet::of(&['a']);
        s.clear();
        assert!(s.is_empty());
    }

    #[test]
    fn test_select_reject() {
        let s = CharHashSet::of(&['a', 'b', 'c', 'd', 'e']);
        assert_eq!(s.select(|v| v > 'c').len(), 2);
        assert_eq!(s.reject(|v| v > 'c').len(), 3);
    }

    #[test]
    fn test_union() {
        let a = CharHashSet::of(&['a', 'b', 'c']);
        let b = CharHashSet::of(&['c', 'd', 'e']);
        assert_eq!(a.union(&b).len(), 5);
    }

    #[test]
    fn test_intersect() {
        let a = CharHashSet::of(&['a', 'b', 'c']);
        let b = CharHashSet::of(&['b', 'c', 'd']);
        assert_eq!(a.intersect(&b).len(), 2);
    }

    #[test]
    fn test_difference() {
        let a = CharHashSet::of(&['a', 'b', 'c']);
        let b = CharHashSet::of(&['b', 'c', 'd']);
        assert_eq!(a.difference(&b).len(), 1);
    }

    #[test]
    fn test_equals() {
        let a = CharHashSet::of(&['a', 'b']);
        let b = CharHashSet::of(&['b', 'a']);
        assert_eq!(a, b);
    }

    #[test]
    fn test_display() {
        let s = CharHashSet::of(&['a']);
        assert!(!s.to_string().is_empty());
    }

    #[test]
    fn test_try_reserve_happy_path() {
        let mut s = CharHashSet::new();
        s.try_reserve(100).unwrap();
    }

    #[test]
    fn test_try_reserve_propagates_capacity_overflow() {
        let mut s = CharHashSet::new();
        assert!(s.try_reserve(usize::MAX / 2).is_err());
    }
}

impl crate::traits::char_collection::CharCollection for CharHashSet {
    fn len(&self) -> usize {
        self.len()
    }
    fn contains(&self, value: char) -> bool {
        self.contains(value)
    }
    fn iter(&self) -> impl Iterator<Item = char> + '_ {
        self.iter()
    }
}

impl crate::traits::char_collection::CharMutableCollection for CharHashSet {
    fn clear(&mut self) {
        self.clear()
    }
}

impl crate::traits::char_collection::CharSet for CharHashSet {}

impl crate::traits::char_collection::CharMutableSet for CharHashSet {
    fn add(&mut self, value: char) -> bool {
        self.add(value)
    }
}
