// Code generated by mapdb-codegen. DO NOT EDIT.

use crate::hash_table::OpenHashSet;
use std::fmt;

/// Hash set of unique `f32` values.
/// Open-addressing with linear probing and Robin Hood backward-shift deletion.
#[derive(Debug, Clone)]
pub struct F32HashSet {
    inner: OpenHashSet<f32>,
}

impl F32HashSet {
    pub fn new() -> Self {
        F32HashSet {
            inner: OpenHashSet::new(),
        }
    }

    pub fn of(values: &[f32]) -> Self {
        let mut s = Self::new();
        for &v in values {
            s.add(v);
        }
        s
    }

    /// Adds a value. Returns true if it was not already present.
    pub fn add(&mut self, value: f32) -> bool {
        self.inner.add(value)
    }

    /// Removes a value. Returns true if it was present.
    pub fn remove(&mut self, value: f32) -> bool {
        self.inner.remove(value)
    }

    pub fn contains(&self, value: f32) -> bool {
        self.inner.contains(value)
    }

    pub fn len(&self) -> usize {
        self.inner.len()
    }

    pub fn is_empty(&self) -> bool {
        self.inner.is_empty()
    }

    pub fn clear(&mut self) {
        self.inner.clear();
    }

    /// Ensures the set can accept `additional` more entries without a
    /// rehash. Returns `TryReserveError` on allocator failure. See
    /// `docs/rust/error-handling.md`.
    pub fn try_reserve(
        &mut self,
        additional: usize,
    ) -> Result<(), std::collections::TryReserveError> {
        self.inner.try_reserve(additional)
    }

    pub fn iter(&self) -> impl Iterator<Item = f32> + '_ {
        self.inner.iter()
    }

    pub fn for_each(&self, mut f: impl FnMut(f32)) {
        for v in self.iter() {
            f(v);
        }
    }

    pub fn select(&self, predicate: impl Fn(f32) -> bool) -> Self {
        let mut result = Self::new();
        for v in self.iter() {
            if predicate(v) {
                result.add(v);
            }
        }
        result
    }

    pub fn reject(&self, predicate: impl Fn(f32) -> bool) -> Self {
        let mut result = Self::new();
        for v in self.iter() {
            if !predicate(v) {
                result.add(v);
            }
        }
        result
    }

    pub fn detect(&self, predicate: impl Fn(f32) -> bool) -> Option<f32> {
        self.iter().find(|&v| predicate(v))
    }

    pub fn any_satisfy(&self, predicate: impl Fn(f32) -> bool) -> bool {
        self.iter().any(predicate)
    }

    pub fn all_satisfy(&self, predicate: impl Fn(f32) -> bool) -> bool {
        self.iter().all(predicate)
    }

    pub fn none_satisfy(&self, predicate: impl Fn(f32) -> bool) -> bool {
        !self.iter().any(predicate)
    }

    pub fn union(&self, other: &Self) -> Self {
        let mut result = self.clone();
        for v in other.iter() {
            result.add(v);
        }
        result
    }

    pub fn intersect(&self, other: &Self) -> Self {
        let mut result = Self::new();
        for v in self.iter() {
            if other.contains(v) {
                result.add(v);
            }
        }
        result
    }

    pub fn difference(&self, other: &Self) -> Self {
        let mut result = Self::new();
        for v in self.iter() {
            if !other.contains(v) {
                result.add(v);
            }
        }
        result
    }

    pub fn symmetric_difference(&self, other: &Self) -> Self {
        let mut result = Self::new();
        for v in self.iter() {
            if !other.contains(v) {
                result.add(v);
            }
        }
        for v in other.iter() {
            if !self.contains(v) {
                result.add(v);
            }
        }
        result
    }

    pub fn to_vec(&self) -> Vec<f32> {
        self.iter().collect()
    }

    pub fn with(mut self, value: f32) -> Self {
        self.add(value);
        self
    }
    pub fn without(mut self, value: f32) -> Self {
        self.remove(value);
        self
    }
}

impl Default for F32HashSet {
    fn default() -> Self {
        Self::new()
    }
}

impl PartialEq for F32HashSet {
    fn eq(&self, other: &Self) -> bool {
        if self.len() != other.len() {
            return false;
        }
        self.iter().all(|v| other.contains(v))
    }
}

impl fmt::Display for F32HashSet {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{{")?;
        let mut first = true;
        for v in self.iter() {
            if !first {
                write!(f, ", ")?;
            }
            write!(f, "{}", v)?;
            first = false;
        }
        write!(f, "}}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_add_contains() {
        let mut s = F32HashSet::new();
        s.add(1.0f32);
        s.add(2.0f32);
        s.add(3.0f32);
        assert_eq!(s.len(), 3);
        assert!(s.contains(2.0f32));
        assert!(!s.contains(99.0f32));
    }

    #[test]
    fn test_add_duplicate() {
        let mut s = F32HashSet::new();
        assert!(s.add(1.0f32));
        assert!(!s.add(1.0f32));
        assert_eq!(s.len(), 1);
    }

    #[test]
    fn test_remove() {
        let mut s = F32HashSet::of(&[1.0f32, 2.0f32, 3.0f32]);
        assert!(s.remove(2.0f32));
        assert!(!s.contains(2.0f32));
        assert!(!s.remove(99.0f32));
    }

    #[test]
    fn test_clear() {
        let mut s = F32HashSet::of(&[1.0f32]);
        s.clear();
        assert!(s.is_empty());
    }

    #[test]
    fn test_select_reject() {
        let s = F32HashSet::of(&[1.0f32, 2.0f32, 3.0f32, 4.0f32, 5.0f32]);
        assert_eq!(s.select(|v| v > 3.0f32).len(), 2);
        assert_eq!(s.reject(|v| v > 3.0f32).len(), 3);
    }

    #[test]
    fn test_union() {
        let a = F32HashSet::of(&[1.0f32, 2.0f32, 3.0f32]);
        let b = F32HashSet::of(&[3.0f32, 4.0f32, 5.0f32]);
        assert_eq!(a.union(&b).len(), 5);
    }

    #[test]
    fn test_intersect() {
        let a = F32HashSet::of(&[1.0f32, 2.0f32, 3.0f32]);
        let b = F32HashSet::of(&[2.0f32, 3.0f32, 4.0f32]);
        assert_eq!(a.intersect(&b).len(), 2);
    }

    #[test]
    fn test_difference() {
        let a = F32HashSet::of(&[1.0f32, 2.0f32, 3.0f32]);
        let b = F32HashSet::of(&[2.0f32, 3.0f32, 4.0f32]);
        assert_eq!(a.difference(&b).len(), 1);
    }

    #[test]
    fn test_equals() {
        let a = F32HashSet::of(&[1.0f32, 2.0f32]);
        let b = F32HashSet::of(&[2.0f32, 1.0f32]);
        assert_eq!(a, b);
    }

    #[test]
    fn test_display() {
        let s = F32HashSet::of(&[1.0f32]);
        assert!(!s.to_string().is_empty());
    }

    #[test]
    fn test_try_reserve_happy_path() {
        let mut s = F32HashSet::new();
        s.try_reserve(100).unwrap();
    }

    #[test]
    fn test_try_reserve_propagates_capacity_overflow() {
        let mut s = F32HashSet::new();
        assert!(s.try_reserve(usize::MAX / 2).is_err());
    }

    // -----------------------------------------------------------------------
    // IEEE 754 edge cases — float element semantics
    // -----------------------------------------------------------------------
    // Locks in bit-level equality:  NaN findable, ±0.0 distinct, ±Inf round-trips.
    // See docs/float-nan-semantics-audit.md.

    #[test]
    fn test_nan_element_findable() {
        let mut s = F32HashSet::new();
        s.add(f32::NAN);
        assert!(s.contains(f32::NAN));
        assert_eq!(s.len(), 1);
    }

    #[test]
    fn test_nan_element_idempotent_add() {
        let mut s = F32HashSet::new();
        s.add(f32::NAN);
        s.add(f32::NAN);
        s.add(f32::NAN);
        assert_eq!(s.len(), 1);
    }

    #[test]
    fn test_nan_element_remove() {
        let mut s = F32HashSet::new();
        s.add(f32::NAN);
        let removed = s.remove(f32::NAN);
        assert!(removed);
        assert_eq!(s.len(), 0);
        assert!(!s.contains(f32::NAN));
    }

    #[test]
    fn test_negative_zero_distinct_from_positive_zero() {
        let mut s = F32HashSet::new();
        s.add(0.0f32);
        s.add(-0.0f32);
        assert_eq!(s.len(), 2);
        assert!(s.contains(0.0f32));
        assert!(s.contains(-0.0f32));
    }

    #[test]
    fn test_infinity_elements() {
        let mut s = F32HashSet::new();
        s.add(f32::INFINITY);
        s.add(f32::NEG_INFINITY);
        assert_eq!(s.len(), 2);
        assert!(s.contains(f32::INFINITY));
        assert!(s.contains(f32::NEG_INFINITY));
    }
}

impl crate::traits::f32_collection::F32Collection for F32HashSet {
    fn len(&self) -> usize {
        self.len()
    }
    fn contains(&self, value: f32) -> bool {
        self.contains(value)
    }
    fn iter(&self) -> impl Iterator<Item = f32> + '_ {
        self.iter()
    }
}

impl crate::traits::f32_collection::F32MutableCollection for F32HashSet {
    fn clear(&mut self) {
        self.clear()
    }
}

impl crate::traits::f32_collection::F32Set for F32HashSet {}

impl crate::traits::f32_collection::F32MutableSet for F32HashSet {
    fn add(&mut self, value: f32) -> bool {
        self.add(value)
    }
}
