// Code generated by mapdb-codegen. DO NOT EDIT.

use std::sync::RwLock;

use super::f64_hash_set::F64HashSet;

/// Thread-safe wrapper around [`F64HashSet`]. Uses an internal `RwLock`
/// so reads may run concurrently while mutations are exclusive.
#[derive(Debug, Default)]
pub struct SynchronizedF64HashSet {
    inner: RwLock<F64HashSet>,
}

impl SynchronizedF64HashSet {
    pub fn new() -> Self {
        SynchronizedF64HashSet {
            inner: RwLock::new(F64HashSet::new()),
        }
    }

    pub fn of(values: &[f64]) -> Self {
        SynchronizedF64HashSet {
            inner: RwLock::new(F64HashSet::of(values)),
        }
    }

    pub fn add(&self, value: f64) -> bool {
        self.inner.write().unwrap().add(value)
    }

    pub fn remove(&self, value: f64) -> bool {
        self.inner.write().unwrap().remove(value)
    }

    pub fn contains(&self, value: f64) -> bool {
        self.inner.read().unwrap().contains(value)
    }

    pub fn len(&self) -> usize {
        self.inner.read().unwrap().len()
    }
    pub fn is_empty(&self) -> bool {
        self.inner.read().unwrap().is_empty()
    }
    pub fn clear(&self) {
        self.inner.write().unwrap().clear();
    }

    pub fn to_vec(&self) -> Vec<f64> {
        self.inner.read().unwrap().to_vec()
    }

    pub fn for_each(&self, f: impl FnMut(f64)) {
        self.inner.read().unwrap().for_each(f);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;
    use std::thread;

    #[test]
    fn test_basic_ops() {
        let s = SynchronizedF64HashSet::new();
        assert!(s.is_empty());
        assert!(s.add(1.0f64));
        assert!(s.add(2.0f64));
        assert!(!s.add(1.0f64));
        assert!(s.contains(1.0f64));
        assert_eq!(s.len(), 2);
        assert!(s.remove(1.0f64));
        assert!(!s.contains(1.0f64));
        s.clear();
        assert!(s.is_empty());
    }

    #[test]
    fn test_to_vec_and_for_each() {
        let s = SynchronizedF64HashSet::of(&[1.0f64, 2.0f64]);
        assert!(s.to_vec().len() >= 1);
        let mut count = 0usize;
        s.for_each(|_| count += 1);
        assert!(count >= 1);
    }

    #[test]
    fn test_concurrent() {
        let s = Arc::new(SynchronizedF64HashSet::new());
        let mut handles = Vec::new();
        for _ in 0..4 {
            let c = Arc::clone(&s);
            handles.push(thread::spawn(move || {
                for _ in 0..100 {
                    c.add(1.0f64);
                    c.contains(1.0f64);
                }
            }));
        }
        for h in handles {
            h.join().unwrap();
        }
        assert!(s.contains(1.0f64));
        assert_eq!(s.len(), 1);
    }
}
