// Code generated by mapdb-codegen. DO NOT EDIT.

use std::sync::RwLock;

use super::char_hash_set::CharHashSet;

/// Thread-safe wrapper around [`CharHashSet`]. Uses an internal `RwLock`
/// so reads may run concurrently while mutations are exclusive.
#[derive(Debug, Default)]
pub struct SynchronizedCharHashSet {
    inner: RwLock<CharHashSet>,
}

impl SynchronizedCharHashSet {
    pub fn new() -> Self {
        SynchronizedCharHashSet {
            inner: RwLock::new(CharHashSet::new()),
        }
    }

    pub fn of(values: &[char]) -> Self {
        SynchronizedCharHashSet {
            inner: RwLock::new(CharHashSet::of(values)),
        }
    }

    pub fn add(&self, value: char) -> bool {
        self.inner.write().unwrap().add(value)
    }

    pub fn remove(&self, value: char) -> bool {
        self.inner.write().unwrap().remove(value)
    }

    pub fn contains(&self, value: char) -> bool {
        self.inner.read().unwrap().contains(value)
    }

    pub fn len(&self) -> usize {
        self.inner.read().unwrap().len()
    }
    pub fn is_empty(&self) -> bool {
        self.inner.read().unwrap().is_empty()
    }
    pub fn clear(&self) {
        self.inner.write().unwrap().clear();
    }

    pub fn to_vec(&self) -> Vec<char> {
        self.inner.read().unwrap().to_vec()
    }

    pub fn for_each(&self, f: impl FnMut(char)) {
        self.inner.read().unwrap().for_each(f);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;
    use std::thread;

    #[test]
    fn test_basic_ops() {
        let s = SynchronizedCharHashSet::new();
        assert!(s.is_empty());
        assert!(s.add('a'));
        assert!(s.add('b'));
        assert!(!s.add('a'));
        assert!(s.contains('a'));
        assert_eq!(s.len(), 2);
        assert!(s.remove('a'));
        assert!(!s.contains('a'));
        s.clear();
        assert!(s.is_empty());
    }

    #[test]
    fn test_to_vec_and_for_each() {
        let s = SynchronizedCharHashSet::of(&['a', 'b']);
        assert!(s.to_vec().len() >= 1);
        let mut count = 0usize;
        s.for_each(|_| count += 1);
        assert!(count >= 1);
    }

    #[test]
    fn test_concurrent() {
        let s = Arc::new(SynchronizedCharHashSet::new());
        let mut handles = Vec::new();
        for _ in 0..4 {
            let c = Arc::clone(&s);
            handles.push(thread::spawn(move || {
                for _ in 0..100 {
                    c.add('a');
                    c.contains('a');
                }
            }));
        }
        for h in handles {
            h.join().unwrap();
        }
        assert!(s.contains('a'));
        assert_eq!(s.len(), 1);
    }
}
