// Code generated by mapdb-codegen. DO NOT EDIT.

use crate::hash_table::OpenHashMap;
use std::fmt;

/// Hash map from `bool` keys to `i8` values.
/// Open-addressing with linear probing and Robin Hood backward-shift deletion.
#[derive(Debug, Clone)]
pub struct BoolI8HashMap {
    inner: OpenHashMap<bool, i8>,
}

impl BoolI8HashMap {
    pub fn new() -> Self {
        BoolI8HashMap {
            inner: OpenHashMap::new(),
        }
    }

    pub fn with_capacity(capacity: usize) -> Self {
        BoolI8HashMap {
            inner: OpenHashMap::with_capacity(capacity),
        }
    }

    /// Inserts a key-value pair. Returns the old value if the key was already present.
    pub fn insert(&mut self, key: bool, value: i8) -> Option<i8> {
        self.inner.insert(key, value)
    }

    /// Returns the value for the key, or None.
    pub fn get(&self, key: bool) -> Option<i8> {
        self.inner.get(key)
    }

    /// Returns the value for the key, or the default.
    pub fn get_or_default(&self, key: bool, default: i8) -> i8 {
        self.inner.get(key).unwrap_or(default)
    }

    /// Removes the key. Returns the old value if present.
    pub fn remove(&mut self, key: bool) -> Option<i8> {
        self.inner.remove(key)
    }

    pub fn contains_key(&self, key: bool) -> bool {
        self.inner.contains_key(key)
    }

    pub fn contains_value(&self, value: i8) -> bool {
        self.inner.iter().any(|(_, v)| v == value)
    }

    pub fn len(&self) -> usize {
        self.inner.len()
    }
    pub fn is_empty(&self) -> bool {
        self.inner.is_empty()
    }
    pub fn clear(&mut self) {
        self.inner.clear();
    }

    /// Ensures the map can accept `additional` more entries without a
    /// rehash. Returns `TryReserveError` on allocator failure. See
    /// `docs/rust/error-handling.md`.
    pub fn try_reserve(
        &mut self,
        additional: usize,
    ) -> Result<(), std::collections::TryReserveError> {
        self.inner.try_reserve(additional)
    }

    /// Iterates over (key, value) pairs.
    pub fn iter(&self) -> impl Iterator<Item = (bool, i8)> + '_ {
        self.inner.iter()
    }

    pub fn keys(&self) -> impl Iterator<Item = bool> + '_ {
        self.inner.iter().map(|(k, _)| k)
    }

    pub fn values(&self) -> impl Iterator<Item = i8> + '_ {
        self.inner.iter().map(|(_, v)| v)
    }

    pub fn for_each(&self, mut f: impl FnMut(bool, i8)) {
        for (k, v) in self.iter() {
            f(k, v);
        }
    }

    pub fn select(&self, predicate: impl Fn(bool, i8) -> bool) -> Self {
        let mut result = Self::new();
        for (k, v) in self.iter() {
            if predicate(k, v) {
                result.insert(k, v);
            }
        }
        result
    }

    pub fn reject(&self, predicate: impl Fn(bool, i8) -> bool) -> Self {
        let mut result = Self::new();
        for (k, v) in self.iter() {
            if !predicate(k, v) {
                result.insert(k, v);
            }
        }
        result
    }

    pub fn detect(&self, predicate: impl Fn(bool, i8) -> bool) -> Option<(bool, i8)> {
        self.iter().find(|&(k, v)| predicate(k, v))
    }

    pub fn any_satisfy(&self, predicate: impl Fn(bool, i8) -> bool) -> bool {
        self.iter().any(|(k, v)| predicate(k, v))
    }

    pub fn all_satisfy(&self, predicate: impl Fn(bool, i8) -> bool) -> bool {
        self.iter().all(|(k, v)| predicate(k, v))
    }

    pub fn none_satisfy(&self, predicate: impl Fn(bool, i8) -> bool) -> bool {
        !self.iter().any(|(k, v)| predicate(k, v))
    }

    pub fn count(&self, predicate: impl Fn(bool, i8) -> bool) -> usize {
        self.iter().filter(|&(k, v)| predicate(k, v)).count()
    }

    pub fn inject_into<R>(&self, initial: R, mut f: impl FnMut(R, bool, i8) -> R) -> R {
        let mut acc = initial;
        for (k, v) in self.iter() {
            acc = f(acc, k, v);
        }
        acc
    }

    pub fn keys_to_vec(&self) -> Vec<bool> {
        self.keys().collect()
    }
    pub fn values_to_vec(&self) -> Vec<i8> {
        self.values().collect()
    }

    pub fn with_key_value(mut self, key: bool, value: i8) -> Self {
        self.insert(key, value);
        self
    }

    pub fn without_key(mut self, key: bool) -> Self {
        self.remove(key);
        self
    }
}

impl Default for BoolI8HashMap {
    fn default() -> Self {
        Self::new()
    }
}

impl PartialEq for BoolI8HashMap {
    fn eq(&self, other: &Self) -> bool {
        if self.len() != other.len() {
            return false;
        }
        self.iter()
            .all(|(k, v)| other.get(k).is_some_and(|ov| v == ov))
    }
}

impl fmt::Display for BoolI8HashMap {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{{")?;
        let mut first = true;
        for (k, v) in self.iter() {
            if !first {
                write!(f, ", ")?;
            }
            write!(f, "{}={}", k, v)?;
            first = false;
        }
        write!(f, "}}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_insert_get() {
        let mut m = BoolI8HashMap::new();
        m.insert(true, 1);
        m.insert(false, 2);
        assert_eq!(m.get(true), Some(1));

        assert_eq!(m.len(), 2);
    }

    #[test]
    fn test_insert_overwrite() {
        let mut m = BoolI8HashMap::new();
        m.insert(true, 1);
        let old = m.insert(true, 2);
        assert_eq!(old, Some(1));
        assert_eq!(m.get(true), Some(2));
    }

    #[test]
    fn test_remove() {
        let mut m = BoolI8HashMap::new();
        m.insert(true, 1);
        m.insert(false, 2);
        assert_eq!(m.remove(true), Some(1));
        assert_eq!(m.len(), 1);
        assert!(!m.contains_key(true));
    }

    #[test]
    fn test_contains_key() {
        let mut m = BoolI8HashMap::new();
        m.insert(true, 1);
        assert!(m.contains_key(true));
        assert!(!m.contains_key(false));
    }

    #[test]
    fn test_get_or_default() {
        let mut m = BoolI8HashMap::new();
        m.insert(true, 1);
        assert_eq!(m.get_or_default(true, 3), 1);
        assert_eq!(m.get_or_default(false, 3), 3);
    }

    #[test]
    fn test_clear() {
        let mut m = BoolI8HashMap::new();
        m.insert(true, 1);
        m.clear();
        assert!(m.is_empty());
    }

    #[test]
    fn test_select_reject() {
        let mut m = BoolI8HashMap::new();
        m.insert(true, 1);
        m.insert(false, 2);
        let sel = m.select(|_k, v| v == 1);
        assert!(sel.len() >= 1);
    }

    #[test]
    fn test_any_all_none() {
        let mut m = BoolI8HashMap::new();
        m.insert(true, 1);
        assert!(m.any_satisfy(|_k, v| v == 1));
    }

    #[test]
    fn test_equals() {
        let mut m1 = BoolI8HashMap::new();
        m1.insert(true, 1);
        m1.insert(false, 2);
        let mut m2 = BoolI8HashMap::new();
        m2.insert(false, 2);
        m2.insert(true, 1);
        assert_eq!(m1, m2);
    }

    #[test]
    fn test_display() {
        let mut m = BoolI8HashMap::new();
        m.insert(true, 1);
        assert!(!m.to_string().is_empty());
    }

    #[test]
    fn test_resize() {
        let mut m = BoolI8HashMap::new();
        for i in 0..100usize {
            m.insert(i % 2 == 0, (i * 10) as i8);
        }
        assert!(m.len() > 0);
    }

    #[test]
    fn test_try_reserve_happy_path() {
        let mut m = BoolI8HashMap::new();
        m.try_reserve(100).unwrap();
    }

    #[test]
    fn test_try_reserve_propagates_capacity_overflow() {
        let mut m = BoolI8HashMap::new();
        assert!(m.try_reserve(usize::MAX / 2).is_err());
    }
}

impl crate::traits::bool_i8_map::BoolI8Map for BoolI8HashMap {
    fn len(&self) -> usize {
        self.len()
    }
    fn contains_key(&self, key: bool) -> bool {
        self.contains_key(key)
    }
    fn get(&self, key: bool) -> Option<i8> {
        self.get(key)
    }
    fn iter(&self) -> impl Iterator<Item = (bool, i8)> + '_ {
        self.iter()
    }
}

impl crate::traits::bool_i8_map::BoolI8MutableMap for BoolI8HashMap {
    fn insert(&mut self, key: bool, value: i8) -> Option<i8> {
        self.insert(key, value)
    }
    fn remove(&mut self, key: bool) -> Option<i8> {
        self.remove(key)
    }
    fn clear(&mut self) {
        self.clear()
    }
}
