// Code generated by mapdb-codegen. DO NOT EDIT.

use crate::hash_table::OpenHashMap;
use std::fmt;

/// Hash map from `char` keys to `f64` values.
/// Open-addressing with linear probing and Robin Hood backward-shift deletion.
#[derive(Debug, Clone)]
pub struct CharF64HashMap {
    inner: OpenHashMap<char, f64>,
}

impl CharF64HashMap {
    pub fn new() -> Self {
        CharF64HashMap {
            inner: OpenHashMap::new(),
        }
    }

    pub fn with_capacity(capacity: usize) -> Self {
        CharF64HashMap {
            inner: OpenHashMap::with_capacity(capacity),
        }
    }

    /// Inserts a key-value pair. Returns the old value if the key was already present.
    pub fn insert(&mut self, key: char, value: f64) -> Option<f64> {
        self.inner.insert(key, value)
    }

    /// Returns the value for the key, or None.
    pub fn get(&self, key: char) -> Option<f64> {
        self.inner.get(key)
    }

    /// Returns the value for the key, or the default.
    pub fn get_or_default(&self, key: char, default: f64) -> f64 {
        self.inner.get(key).unwrap_or(default)
    }

    /// Removes the key. Returns the old value if present.
    pub fn remove(&mut self, key: char) -> Option<f64> {
        self.inner.remove(key)
    }

    pub fn contains_key(&self, key: char) -> bool {
        self.inner.contains_key(key)
    }

    pub fn contains_value(&self, value: f64) -> bool {
        self.inner
            .iter()
            .any(|(_, v)| v.to_bits() == value.to_bits())
    }

    pub fn len(&self) -> usize {
        self.inner.len()
    }
    pub fn is_empty(&self) -> bool {
        self.inner.is_empty()
    }
    pub fn clear(&mut self) {
        self.inner.clear();
    }

    /// Ensures the map can accept `additional` more entries without a
    /// rehash. Returns `TryReserveError` on allocator failure. See
    /// `docs/rust/error-handling.md`.
    pub fn try_reserve(
        &mut self,
        additional: usize,
    ) -> Result<(), std::collections::TryReserveError> {
        self.inner.try_reserve(additional)
    }

    /// Iterates over (key, value) pairs.
    pub fn iter(&self) -> impl Iterator<Item = (char, f64)> + '_ {
        self.inner.iter()
    }

    pub fn keys(&self) -> impl Iterator<Item = char> + '_ {
        self.inner.iter().map(|(k, _)| k)
    }

    pub fn values(&self) -> impl Iterator<Item = f64> + '_ {
        self.inner.iter().map(|(_, v)| v)
    }

    pub fn for_each(&self, mut f: impl FnMut(char, f64)) {
        for (k, v) in self.iter() {
            f(k, v);
        }
    }

    pub fn select(&self, predicate: impl Fn(char, f64) -> bool) -> Self {
        let mut result = Self::new();
        for (k, v) in self.iter() {
            if predicate(k, v) {
                result.insert(k, v);
            }
        }
        result
    }

    pub fn reject(&self, predicate: impl Fn(char, f64) -> bool) -> Self {
        let mut result = Self::new();
        for (k, v) in self.iter() {
            if !predicate(k, v) {
                result.insert(k, v);
            }
        }
        result
    }

    pub fn detect(&self, predicate: impl Fn(char, f64) -> bool) -> Option<(char, f64)> {
        self.iter().find(|&(k, v)| predicate(k, v))
    }

    pub fn any_satisfy(&self, predicate: impl Fn(char, f64) -> bool) -> bool {
        self.iter().any(|(k, v)| predicate(k, v))
    }

    pub fn all_satisfy(&self, predicate: impl Fn(char, f64) -> bool) -> bool {
        self.iter().all(|(k, v)| predicate(k, v))
    }

    pub fn none_satisfy(&self, predicate: impl Fn(char, f64) -> bool) -> bool {
        !self.iter().any(|(k, v)| predicate(k, v))
    }

    pub fn count(&self, predicate: impl Fn(char, f64) -> bool) -> usize {
        self.iter().filter(|&(k, v)| predicate(k, v)).count()
    }

    pub fn inject_into<R>(&self, initial: R, mut f: impl FnMut(R, char, f64) -> R) -> R {
        let mut acc = initial;
        for (k, v) in self.iter() {
            acc = f(acc, k, v);
        }
        acc
    }

    pub fn keys_to_vec(&self) -> Vec<char> {
        self.keys().collect()
    }
    pub fn values_to_vec(&self) -> Vec<f64> {
        self.values().collect()
    }

    pub fn with_key_value(mut self, key: char, value: f64) -> Self {
        self.insert(key, value);
        self
    }

    pub fn without_key(mut self, key: char) -> Self {
        self.remove(key);
        self
    }
}

impl Default for CharF64HashMap {
    fn default() -> Self {
        Self::new()
    }
}

impl PartialEq for CharF64HashMap {
    fn eq(&self, other: &Self) -> bool {
        if self.len() != other.len() {
            return false;
        }
        self.iter()
            .all(|(k, v)| other.get(k).is_some_and(|ov| v.to_bits() == ov.to_bits()))
    }
}

impl fmt::Display for CharF64HashMap {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{{")?;
        let mut first = true;
        for (k, v) in self.iter() {
            if !first {
                write!(f, ", ")?;
            }
            write!(f, "{}={}", k, v)?;
            first = false;
        }
        write!(f, "}}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_insert_get() {
        let mut m = CharF64HashMap::new();
        m.insert('a', 1.0f64);
        m.insert('b', 2.0f64);
        m.insert('c', 3.0f64);
        assert_eq!(m.get('a'), Some(1.0f64));
        assert_eq!(m.get('z'), None);
        assert_eq!(m.len(), 3);
    }

    #[test]
    fn test_insert_overwrite() {
        let mut m = CharF64HashMap::new();
        m.insert('a', 1.0f64);
        let old = m.insert('a', 2.0f64);
        assert_eq!(old, Some(1.0f64));
        assert_eq!(m.get('a'), Some(2.0f64));
    }

    #[test]
    fn test_remove() {
        let mut m = CharF64HashMap::new();
        m.insert('a', 1.0f64);
        m.insert('b', 2.0f64);
        assert_eq!(m.remove('a'), Some(1.0f64));
        assert_eq!(m.len(), 1);
        assert!(!m.contains_key('a'));
    }

    #[test]
    fn test_contains_key() {
        let mut m = CharF64HashMap::new();
        m.insert('a', 1.0f64);
        assert!(m.contains_key('a'));
        assert!(!m.contains_key('z'));
    }

    #[test]
    fn test_get_or_default() {
        let mut m = CharF64HashMap::new();
        m.insert('a', 1.0f64);
        assert_eq!(m.get_or_default('a', 3.0f64), 1.0f64);
        assert_eq!(m.get_or_default('z', 3.0f64), 3.0f64);
    }

    #[test]
    fn test_clear() {
        let mut m = CharF64HashMap::new();
        m.insert('a', 1.0f64);
        m.clear();
        assert!(m.is_empty());
    }

    #[test]
    fn test_select_reject() {
        let mut m = CharF64HashMap::new();
        m.insert('a', 1.0f64);
        m.insert('b', 2.0f64);
        m.insert('c', 3.0f64);
        assert_eq!(m.select(|_k, v| v > 1.0f64).len(), 2);
        assert_eq!(m.reject(|_k, v| v > 1.0f64).len(), 1);
    }

    #[test]
    fn test_any_all_none() {
        let mut m = CharF64HashMap::new();
        m.insert('a', 1.0f64);
        m.insert('b', 2.0f64);
        assert!(m.any_satisfy(|_k, v| v == 2.0f64));
        assert!(m.all_satisfy(|_k, v| v > 0.0));
        assert!(m.none_satisfy(|_k, v| v == 99.0f64));
    }

    #[test]
    fn test_equals() {
        let mut m1 = CharF64HashMap::new();
        m1.insert('a', 1.0f64);
        m1.insert('b', 2.0f64);
        let mut m2 = CharF64HashMap::new();
        m2.insert('b', 2.0f64);
        m2.insert('a', 1.0f64);
        assert_eq!(m1, m2);
    }

    #[test]
    fn test_display() {
        let mut m = CharF64HashMap::new();
        m.insert('a', 1.0f64);
        assert!(!m.to_string().is_empty());
    }

    #[test]
    fn test_resize() {
        let mut m = CharF64HashMap::new();
        for i in 0..100 {
            m.insert(char::from(b'a' + (i % 26) as u8), (i * 10) as f64);
        }
        assert!(m.len() > 0);
    }

    #[test]
    fn test_try_reserve_happy_path() {
        let mut m = CharF64HashMap::new();
        m.try_reserve(100).unwrap();
    }

    #[test]
    fn test_try_reserve_propagates_capacity_overflow() {
        let mut m = CharF64HashMap::new();
        assert!(m.try_reserve(usize::MAX / 2).is_err());
    }
}

impl crate::traits::char_f64_map::CharF64Map for CharF64HashMap {
    fn len(&self) -> usize {
        self.len()
    }
    fn contains_key(&self, key: char) -> bool {
        self.contains_key(key)
    }
    fn get(&self, key: char) -> Option<f64> {
        self.get(key)
    }
    fn iter(&self) -> impl Iterator<Item = (char, f64)> + '_ {
        self.iter()
    }
}

impl crate::traits::char_f64_map::CharF64MutableMap for CharF64HashMap {
    fn insert(&mut self, key: char, value: f64) -> Option<f64> {
        self.insert(key, value)
    }
    fn remove(&mut self, key: char) -> Option<f64> {
        self.remove(key)
    }
    fn clear(&mut self) {
        self.clear()
    }
}
