// Code generated by mapdb-codegen. DO NOT EDIT.

use std::sync::RwLock;

use super::f32_bool_hash_map::F32BoolHashMap;

/// Thread-safe wrapper around [`F32BoolHashMap`]. Reads are concurrent;
/// mutations are exclusive. Lock poisoning panics (parity with Go).
#[derive(Debug, Default)]
pub struct SynchronizedF32BoolHashMap {
    inner: RwLock<F32BoolHashMap>,
}

impl SynchronizedF32BoolHashMap {
    pub fn new() -> Self {
        SynchronizedF32BoolHashMap {
            inner: RwLock::new(F32BoolHashMap::new()),
        }
    }

    pub fn with_capacity(capacity: usize) -> Self {
        SynchronizedF32BoolHashMap {
            inner: RwLock::new(F32BoolHashMap::with_capacity(capacity)),
        }
    }

    pub fn insert(&self, key: f32, value: bool) -> Option<bool> {
        self.inner.write().unwrap().insert(key, value)
    }

    pub fn get(&self, key: f32) -> Option<bool> {
        self.inner.read().unwrap().get(key)
    }

    pub fn get_or_default(&self, key: f32, default: bool) -> bool {
        self.inner.read().unwrap().get_or_default(key, default)
    }

    pub fn remove(&self, key: f32) -> Option<bool> {
        self.inner.write().unwrap().remove(key)
    }

    pub fn contains_key(&self, key: f32) -> bool {
        self.inner.read().unwrap().contains_key(key)
    }

    pub fn contains_value(&self, value: bool) -> bool {
        self.inner.read().unwrap().contains_value(value)
    }

    pub fn len(&self) -> usize {
        self.inner.read().unwrap().len()
    }
    pub fn is_empty(&self) -> bool {
        self.inner.read().unwrap().is_empty()
    }
    pub fn clear(&self) {
        self.inner.write().unwrap().clear();
    }

    pub fn keys_to_vec(&self) -> Vec<f32> {
        self.inner.read().unwrap().keys_to_vec()
    }

    pub fn values_to_vec(&self) -> Vec<bool> {
        self.inner.read().unwrap().values_to_vec()
    }

    /// Returns an owned snapshot of entries for iteration under read lock.
    pub fn to_vec(&self) -> Vec<(f32, bool)> {
        self.inner.read().unwrap().iter().collect()
    }

    pub fn for_each(&self, mut f: impl FnMut(f32, bool)) {
        let snap = self.to_vec();
        for (k, v) in snap {
            f(k, v);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;
    use std::thread;

    #[test]
    fn test_basic_ops() {
        let m = SynchronizedF32BoolHashMap::new();
        assert!(m.is_empty());
        assert_eq!(m.insert(1.0f32, true), None);
        assert_eq!(m.insert(2.0f32, false), None);
        assert_eq!(m.insert(3.0f32, true), None);
        assert_eq!(m.get(1.0f32), Some(true));
        assert!(m.contains_key(1.0f32));
        assert!(m.contains_value(false));
        let old = m.insert(1.0f32, false);
        assert_eq!(old, Some(true));
        assert_eq!(m.remove(1.0f32), Some(false));
        assert!(!m.contains_key(1.0f32));
        m.clear();
        assert!(m.is_empty());
    }

    #[test]
    fn test_get_or_default() {
        let m = SynchronizedF32BoolHashMap::new();
        m.insert(1.0f32, true);
        assert_eq!(m.get_or_default(1.0f32, true), true);
        assert_eq!(m.get_or_default(99.0f32, true), true);
    }

    #[test]
    fn test_snapshots_and_for_each() {
        let m = SynchronizedF32BoolHashMap::new();
        m.insert(1.0f32, true);
        m.insert(2.0f32, false);
        assert_eq!(m.keys_to_vec().len(), 2);
        assert_eq!(m.values_to_vec().len(), 2);
        assert_eq!(m.to_vec().len(), 2);
        let mut count = 0usize;
        m.for_each(|_, _| count += 1);
        assert_eq!(count, 2);
    }

    #[test]
    fn test_concurrent() {
        let m = Arc::new(SynchronizedF32BoolHashMap::new());
        let mut handles = Vec::new();
        for _ in 0..4 {
            let c = Arc::clone(&m);
            handles.push(thread::spawn(move || {
                for _ in 0..100 {
                    c.insert(1.0f32, true);
                    c.get(1.0f32);
                }
            }));
        }
        for h in handles {
            h.join().unwrap();
        }
        assert_eq!(m.len(), 1);
        assert_eq!(m.get(1.0f32), Some(true));
    }
}
