// Code generated by mapdb-codegen. DO NOT EDIT.

use std::sync::RwLock;

use super::i8_char_hash_map::I8CharHashMap;

/// Thread-safe wrapper around [`I8CharHashMap`]. Reads are concurrent;
/// mutations are exclusive. Lock poisoning panics (parity with Go).
#[derive(Debug, Default)]
pub struct SynchronizedI8CharHashMap {
    inner: RwLock<I8CharHashMap>,
}

impl SynchronizedI8CharHashMap {
    pub fn new() -> Self {
        SynchronizedI8CharHashMap {
            inner: RwLock::new(I8CharHashMap::new()),
        }
    }

    pub fn with_capacity(capacity: usize) -> Self {
        SynchronizedI8CharHashMap {
            inner: RwLock::new(I8CharHashMap::with_capacity(capacity)),
        }
    }

    pub fn insert(&self, key: i8, value: char) -> Option<char> {
        self.inner.write().unwrap().insert(key, value)
    }

    pub fn get(&self, key: i8) -> Option<char> {
        self.inner.read().unwrap().get(key)
    }

    pub fn get_or_default(&self, key: i8, default: char) -> char {
        self.inner.read().unwrap().get_or_default(key, default)
    }

    pub fn remove(&self, key: i8) -> Option<char> {
        self.inner.write().unwrap().remove(key)
    }

    pub fn contains_key(&self, key: i8) -> bool {
        self.inner.read().unwrap().contains_key(key)
    }

    pub fn contains_value(&self, value: char) -> bool {
        self.inner.read().unwrap().contains_value(value)
    }

    pub fn len(&self) -> usize {
        self.inner.read().unwrap().len()
    }
    pub fn is_empty(&self) -> bool {
        self.inner.read().unwrap().is_empty()
    }
    pub fn clear(&self) {
        self.inner.write().unwrap().clear();
    }

    pub fn keys_to_vec(&self) -> Vec<i8> {
        self.inner.read().unwrap().keys_to_vec()
    }

    pub fn values_to_vec(&self) -> Vec<char> {
        self.inner.read().unwrap().values_to_vec()
    }

    /// Returns an owned snapshot of entries for iteration under read lock.
    pub fn to_vec(&self) -> Vec<(i8, char)> {
        self.inner.read().unwrap().iter().collect()
    }

    pub fn for_each(&self, mut f: impl FnMut(i8, char)) {
        let snap = self.to_vec();
        for (k, v) in snap {
            f(k, v);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;
    use std::thread;

    #[test]
    fn test_basic_ops() {
        let m = SynchronizedI8CharHashMap::new();
        assert!(m.is_empty());
        assert_eq!(m.insert(1, 'a'), None);
        assert_eq!(m.insert(2, 'b'), None);
        assert_eq!(m.insert(3, 'c'), None);
        assert_eq!(m.get(1), Some('a'));
        assert!(m.contains_key(1));
        assert!(m.contains_value('b'));
        let old = m.insert(1, 'b');
        assert_eq!(old, Some('a'));
        assert_eq!(m.remove(1), Some('b'));
        assert!(!m.contains_key(1));
        m.clear();
        assert!(m.is_empty());
    }

    #[test]
    fn test_get_or_default() {
        let m = SynchronizedI8CharHashMap::new();
        m.insert(1, 'a');
        assert_eq!(m.get_or_default(1, 'c'), 'a');
        assert_eq!(m.get_or_default(99, 'c'), 'c');
    }

    #[test]
    fn test_snapshots_and_for_each() {
        let m = SynchronizedI8CharHashMap::new();
        m.insert(1, 'a');
        m.insert(2, 'b');
        assert_eq!(m.keys_to_vec().len(), 2);
        assert_eq!(m.values_to_vec().len(), 2);
        assert_eq!(m.to_vec().len(), 2);
        let mut count = 0usize;
        m.for_each(|_, _| count += 1);
        assert_eq!(count, 2);
    }

    #[test]
    fn test_concurrent() {
        let m = Arc::new(SynchronizedI8CharHashMap::new());
        let mut handles = Vec::new();
        for _ in 0..4 {
            let c = Arc::clone(&m);
            handles.push(thread::spawn(move || {
                for _ in 0..100 {
                    c.insert(1, 'a');
                    c.get(1);
                }
            }));
        }
        for h in handles {
            h.join().unwrap();
        }
        assert_eq!(m.len(), 1);
        assert_eq!(m.get(1), Some('a'));
    }
}
