// Code generated by mapdb-codegen. DO NOT EDIT.

use crate::arraylist::f32_array_list::F32ArrayList;
use std::fmt;
use std::sync::Arc;

/// Immutable, cheaply cloneable list of `f32` values.
/// Backed by `Arc<[f32]>` — clone is O(1).
#[derive(Debug, Clone)]
pub struct ImmutableF32ArrayList {
    items: Arc<[f32]>,
}

impl ImmutableF32ArrayList {
    /// Creates from a mutable list (consumes the data).
    pub fn from_mutable(list: &F32ArrayList) -> Self {
        ImmutableF32ArrayList {
            items: Arc::from(list.to_vec().into_boxed_slice()),
        }
    }

    /// Creates from a slice.
    pub fn of(values: &[f32]) -> Self {
        ImmutableF32ArrayList {
            items: Arc::from(values),
        }
    }

    pub fn get(&self, index: usize) -> Option<f32> {
        self.items.get(index).copied()
    }
    pub fn len(&self) -> usize {
        self.items.len()
    }
    pub fn is_empty(&self) -> bool {
        self.items.is_empty()
    }

    /// Returns the index of the first occurrence of `value`, or None if not found.
    pub fn index_of(&self, value: f32) -> Option<usize> {
        self.items
            .iter()
            .position(|&v| v.to_bits() == value.to_bits())
    }

    pub fn contains(&self, value: f32) -> bool {
        self.items.iter().any(|&v| v.to_bits() == value.to_bits())
    }

    pub fn iter(&self) -> impl Iterator<Item = f32> + '_ {
        self.items.iter().copied()
    }

    pub fn select(&self, predicate: impl Fn(f32) -> bool) -> Self {
        let items: Vec<f32> = self
            .items
            .iter()
            .copied()
            .filter(|&v| predicate(v))
            .collect();
        ImmutableF32ArrayList {
            items: Arc::from(items.into_boxed_slice()),
        }
    }

    pub fn reject(&self, predicate: impl Fn(f32) -> bool) -> Self {
        let items: Vec<f32> = self
            .items
            .iter()
            .copied()
            .filter(|&v| !predicate(v))
            .collect();
        ImmutableF32ArrayList {
            items: Arc::from(items.into_boxed_slice()),
        }
    }

    pub fn detect(&self, predicate: impl Fn(f32) -> bool) -> Option<f32> {
        self.items.iter().copied().find(|&v| predicate(v))
    }

    pub fn any_satisfy(&self, predicate: impl Fn(f32) -> bool) -> bool {
        self.items.iter().any(|&v| predicate(v))
    }

    pub fn to_vec(&self) -> Vec<f32> {
        self.items.to_vec()
    }

    /// Converts back to a mutable list.
    pub fn to_mutable(&self) -> F32ArrayList {
        F32ArrayList::of(&self.items)
    }
}

impl PartialEq for ImmutableF32ArrayList {
    fn eq(&self, other: &Self) -> bool {
        if self.items.len() != other.items.len() {
            return false;
        }
        self.items
            .iter()
            .zip(other.items.iter())
            .all(|(a, b)| a.to_bits() == b.to_bits())
    }
}

impl fmt::Display for ImmutableF32ArrayList {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "[")?;
        for (i, v) in self.items.iter().enumerate() {
            if i > 0 {
                write!(f, ", ")?;
            }
            write!(f, "{}", v)?;
        }
        write!(f, "]")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_of_and_get() {
        let im = ImmutableF32ArrayList::of(&[1.0f32, 2.0f32, 3.0f32]);
        assert_eq!(im.len(), 3);
        assert_eq!(im.get(1), Some(2.0f32));
    }

    #[test]
    fn test_contains() {
        let im = ImmutableF32ArrayList::of(&[1.0f32, 2.0f32]);
        assert!(im.contains(1.0f32));
    }

    #[test]
    fn test_clone_is_cheap() {
        let im = ImmutableF32ArrayList::of(&[1.0f32, 2.0f32]);
        let im2 = im.clone();
        assert_eq!(im, im2);
    }

    #[test]
    fn test_to_mutable_independent() {
        let im = ImmutableF32ArrayList::of(&[1.0f32]);
        let mut m = im.to_mutable();
        m.push(2.0f32);
        assert_eq!(im.len(), 1);
        assert_eq!(m.len(), 2);
    }

    #[test]
    fn test_display() {
        let im = ImmutableF32ArrayList::of(&[1.0f32]);
        assert!(!im.to_string().is_empty());
    }
}

impl crate::traits::f32_collection::F32Collection for ImmutableF32ArrayList {
    fn len(&self) -> usize {
        self.len()
    }
    fn contains(&self, value: f32) -> bool {
        self.contains(value)
    }
    fn iter(&self) -> impl Iterator<Item = f32> + '_ {
        self.iter()
    }
}

impl crate::traits::f32_collection::F32List for ImmutableF32ArrayList {
    fn get(&self, index: usize) -> Option<f32> {
        self.get(index)
    }
    fn index_of(&self, value: f32) -> Option<usize> {
        self.index_of(value)
    }
}
