// Code generated by mapdb-codegen. DO NOT EDIT.
use crate::hashset::bool_hash_set::BoolHashSet;
use std::fmt;
use std::sync::Arc;

/// Immutable, cheaply cloneable set of `bool` values.
#[derive(Debug, Clone)]
pub struct ImmutableBoolHashSet {
    items: Arc<[bool]>,
}

impl ImmutableBoolHashSet {
    pub fn from_mutable(set: &BoolHashSet) -> Self {
        ImmutableBoolHashSet {
            items: Arc::from(set.to_vec().into_boxed_slice()),
        }
    }
    pub fn of(values: &[bool]) -> Self {
        let mut s = BoolHashSet::new();
        for &v in values {
            s.add(v);
        }
        Self::from_mutable(&s)
    }
    pub fn contains(&self, value: bool) -> bool {
        self.items.contains(&value)
    }
    pub fn len(&self) -> usize {
        self.items.len()
    }
    pub fn is_empty(&self) -> bool {
        self.items.is_empty()
    }
    pub fn iter(&self) -> impl Iterator<Item = bool> + '_ {
        self.items.iter().copied()
    }
    pub fn select(&self, predicate: impl Fn(bool) -> bool) -> Self {
        let items: Vec<bool> = self
            .items
            .iter()
            .copied()
            .filter(|&v| predicate(v))
            .collect();
        ImmutableBoolHashSet {
            items: Arc::from(items.into_boxed_slice()),
        }
    }
    pub fn to_vec(&self) -> Vec<bool> {
        self.items.to_vec()
    }
    pub fn to_mutable(&self) -> BoolHashSet {
        BoolHashSet::of(&self.items)
    }
}

impl PartialEq for ImmutableBoolHashSet {
    fn eq(&self, other: &Self) -> bool {
        if self.len() != other.len() {
            return false;
        }
        self.items.iter().all(|&v| other.contains(v))
    }
}
impl fmt::Display for ImmutableBoolHashSet {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{{")?;
        for (i, v) in self.items.iter().enumerate() {
            if i > 0 {
                write!(f, ", ")?;
            }
            write!(f, "{}", v)?;
        }
        write!(f, "}}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_of_contains() {
        let im = ImmutableBoolHashSet::of(&[true, false]);
        assert!(im.contains(true));
        assert_eq!(im.len(), 2);
    }
    #[test]
    fn test_clone_cheap() {
        let im = ImmutableBoolHashSet::of(&[true]);
        let im2 = im.clone();
        assert_eq!(im, im2);
    }
    #[test]
    fn test_to_mutable_independent() {
        let im = ImmutableBoolHashSet::of(&[true]);
        let mut m = im.to_mutable();
        m.add(false);
        assert_eq!(im.len(), 1);
    }
    #[test]
    fn test_display() {
        assert!(!ImmutableBoolHashSet::of(&[true]).to_string().is_empty());
    }
}

impl crate::traits::bool_collection::BoolCollection for ImmutableBoolHashSet {
    fn len(&self) -> usize {
        self.len()
    }
    fn contains(&self, value: bool) -> bool {
        self.contains(value)
    }
    fn iter(&self) -> impl Iterator<Item = bool> + '_ {
        self.iter()
    }
}

impl crate::traits::bool_collection::BoolSet for ImmutableBoolHashSet {}
