// Code generated by mapdb-codegen. DO NOT EDIT.
use crate::bag::i16_hash_bag::I16HashBag;
use std::collections::HashMap;
use std::fmt;

/// Immutable bag (multiset) of `i16` values with occurrence counts.
#[derive(Debug, Clone)]
pub struct ImmutableI16HashBag {
    counts: HashMap<i16, usize>,
    size: usize,
}

impl ImmutableI16HashBag {
    pub fn from_mutable(bag: &I16HashBag) -> Self {
        let mut im = ImmutableI16HashBag {
            counts: HashMap::new(),
            size: 0,
        };
        bag.for_each_with_occurrences(|v, c| {
            im.counts.insert(v, c);
            im.size += c;
        });
        im
    }
    pub fn of(values: &[i16]) -> Self {
        let m = I16HashBag::of(values);
        Self::from_mutable(&m)
    }
    pub fn occurrences_of(&self, value: i16) -> usize {
        self.counts.get(&value).copied().unwrap_or(0)
    }
    pub fn contains(&self, value: i16) -> bool {
        self.occurrences_of(value) > 0
    }
    pub fn size(&self) -> usize {
        self.size
    }
    pub fn size_distinct(&self) -> usize {
        self.counts.len()
    }
    pub fn is_empty(&self) -> bool {
        self.size == 0
    }
    /// Iterates over all elements, repeating each value by its count.
    pub fn iter(&self) -> impl Iterator<Item = i16> + '_ {
        self.counts
            .iter()
            .flat_map(|(&v, &c)| std::iter::repeat_n(v, c))
    }
    pub fn to_mutable(&self) -> I16HashBag {
        let mut m = I16HashBag::new();
        for (&v, &c) in &self.counts {
            for _ in 0..c {
                m.add(v);
            }
        }
        m
    }
    /// Expands the bag to a `Vec` containing each value repeated by its count.
    pub fn to_vec(&self) -> Vec<i16> {
        let mut out = Vec::with_capacity(self.size);
        for (&v, &c) in &self.counts {
            for _ in 0..c {
                out.push(v);
            }
        }
        out
    }
}

impl crate::traits::i16_collection::I16Collection for ImmutableI16HashBag {
    fn len(&self) -> usize {
        self.size()
    }
    fn contains(&self, value: i16) -> bool {
        self.contains(value)
    }
    fn iter(&self) -> impl Iterator<Item = i16> + '_ {
        self.iter()
    }
}

impl crate::traits::i16_collection::I16Bag for ImmutableI16HashBag {
    fn occurrences_of(&self, value: i16) -> usize {
        self.occurrences_of(value)
    }
    fn size_distinct(&self) -> usize {
        self.size_distinct()
    }
}

impl fmt::Display for ImmutableI16HashBag {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "ImmutableBag(size={})", self.size)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_occurrences() {
        let im = ImmutableI16HashBag::of(&[1, 1, 2]);
        assert_eq!(im.occurrences_of(1), 2);
        assert_eq!(im.size(), 3);
    }
    #[test]
    fn test_to_mutable() {
        let im = ImmutableI16HashBag::of(&[1]);
        let mut m = im.to_mutable();
        m.add(2);
        assert_eq!(im.size(), 1);
    }
    #[test]
    fn test_display() {
        assert!(!ImmutableI16HashBag::of(&[1]).to_string().is_empty());
    }
}
