// Code generated by mapdb-codegen. DO NOT EDIT.
use crate::hashmap::i16_bool_hash_map::I16BoolHashMap;
use std::collections::HashMap;
use std::fmt;

/// Immutable hash map from `i16` keys to `bool` values. Clone is cheap (shared data).
#[derive(Debug, Clone)]
pub struct ImmutableI16BoolHashMap {
    inner: HashMap<i16, bool>,
}

impl ImmutableI16BoolHashMap {
    pub fn from_mutable(m: &I16BoolHashMap) -> Self {
        let mut inner = HashMap::new();
        m.for_each(|k, v| {
            inner.insert(k, v);
        });
        ImmutableI16BoolHashMap { inner }
    }
    pub fn get(&self, key: i16) -> Option<bool> {
        self.inner.get(&(key)).copied()
    }
    pub fn get_or_default(&self, key: i16, default: bool) -> bool {
        self.get(key).unwrap_or(default)
    }
    pub fn contains_key(&self, key: i16) -> bool {
        self.inner.contains_key(&(key))
    }
    pub fn len(&self) -> usize {
        self.inner.len()
    }
    pub fn is_empty(&self) -> bool {
        self.inner.is_empty()
    }
    pub fn iter(&self) -> impl Iterator<Item = (i16, bool)> + '_ {
        self.inner.iter().map(|(k, &v)| (*k, v))
    }
    pub fn keys(&self) -> impl Iterator<Item = i16> + '_ {
        self.inner.keys().copied()
    }
    pub fn values(&self) -> impl Iterator<Item = bool> + '_ {
        self.inner.values().copied()
    }
    pub fn for_each(&self, mut f: impl FnMut(i16, bool)) {
        for (k, v) in self.iter() {
            f(k, v);
        }
    }
    pub fn select(&self, predicate: impl Fn(i16, bool) -> bool) -> Self {
        let mut inner = HashMap::new();
        for (k, v) in self.iter() {
            if predicate(k, v) {
                inner.insert(k, v);
            }
        }
        ImmutableI16BoolHashMap { inner }
    }
    pub fn any_satisfy(&self, predicate: impl Fn(i16, bool) -> bool) -> bool {
        self.iter().any(|(k, v)| predicate(k, v))
    }
    pub fn all_satisfy(&self, predicate: impl Fn(i16, bool) -> bool) -> bool {
        self.iter().all(|(k, v)| predicate(k, v))
    }
    pub fn to_mutable(&self) -> I16BoolHashMap {
        let mut m = I16BoolHashMap::new();
        for (k, v) in self.iter() {
            m.insert(k, v);
        }
        m
    }
}
impl PartialEq for ImmutableI16BoolHashMap {
    fn eq(&self, other: &Self) -> bool {
        if self.len() != other.len() {
            return false;
        }
        self.iter()
            .all(|(k, v)| other.get(k).is_some_and(|ov| v == ov))
    }
}
impl fmt::Display for ImmutableI16BoolHashMap {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{{")?;
        let mut first = true;
        for (k, v) in self.iter() {
            if !first {
                write!(f, ", ")?;
            }
            write!(f, "{}={}", k, v)?;
            first = false;
        }
        write!(f, "}}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_get() {
        let mut m = I16BoolHashMap::new();
        m.insert(1, true);
        m.insert(2, false);
        let im = ImmutableI16BoolHashMap::from_mutable(&m);
        assert_eq!(im.get(1), Some(true));
        assert_eq!(im.len(), 2);
        assert_eq!(im.get(99), None);
    }
    #[test]
    fn test_contains_key() {
        let mut m = I16BoolHashMap::new();
        m.insert(1, true);
        let im = ImmutableI16BoolHashMap::from_mutable(&m);
        assert!(im.contains_key(1));
    }
    #[test]
    fn test_to_mutable_independent() {
        let mut m = I16BoolHashMap::new();
        m.insert(1, true);
        let im = ImmutableI16BoolHashMap::from_mutable(&m);
        let mut m2 = im.to_mutable();
        m2.insert(2, false);
        assert_eq!(im.len(), 1);
    }
    #[test]
    fn test_display() {
        let mut m = I16BoolHashMap::new();
        m.insert(1, true);
        assert!(!ImmutableI16BoolHashMap::from_mutable(&m)
            .to_string()
            .is_empty());
    }
}

impl crate::traits::i16_bool_map::I16BoolMap for ImmutableI16BoolHashMap {
    fn len(&self) -> usize {
        self.len()
    }
    fn contains_key(&self, key: i16) -> bool {
        self.contains_key(key)
    }
    fn get(&self, key: i16) -> Option<bool> {
        self.get(key)
    }
    fn iter(&self) -> impl Iterator<Item = (i16, bool)> + '_ {
        self.iter()
    }
}
