// Code generated by mapdb-codegen. DO NOT EDIT.
use crate::stack::f64_array_stack::F64ArrayStack;
use std::fmt;
use std::sync::Arc;

/// Immutable stack. Push/pop return new stacks (persistent data structure).
#[derive(Debug, Clone)]
pub struct ImmutableF64ArrayStack {
    items: Arc<[f64]>,
}

impl ImmutableF64ArrayStack {
    pub fn from_mutable(stack: &F64ArrayStack) -> Self {
        ImmutableF64ArrayStack {
            items: Arc::from(stack.to_vec().into_boxed_slice()),
        }
    }
    pub fn of(values: &[f64]) -> Self {
        ImmutableF64ArrayStack {
            items: Arc::from(values),
        }
    }
    pub fn peek(&self) -> Option<f64> {
        self.items.first().copied()
    }
    pub fn len(&self) -> usize {
        self.items.len()
    }
    pub fn is_empty(&self) -> bool {
        self.items.is_empty()
    }

    /// Returns (new stack without top, popped value).
    pub fn pop(&self) -> Option<(Self, f64)> {
        if self.items.is_empty() {
            return None;
        }
        let val = self.items[0];
        let rest: Vec<f64> = self.items[1..].to_vec();
        Some((
            ImmutableF64ArrayStack {
                items: Arc::from(rest.into_boxed_slice()),
            },
            val,
        ))
    }

    /// Returns a new stack with the value pushed on top.
    pub fn push(&self, value: f64) -> Self {
        let mut items = vec![value];
        items.extend_from_slice(&self.items);
        ImmutableF64ArrayStack {
            items: Arc::from(items.into_boxed_slice()),
        }
    }

    pub fn to_mutable(&self) -> F64ArrayStack {
        F64ArrayStack::of(&self.items)
    }
    pub fn contains(&self, value: f64) -> bool {
        self.items.iter().any(|&v| v.to_bits() == value.to_bits())
    }
    pub fn iter(&self) -> impl Iterator<Item = f64> + '_ {
        self.items.iter().copied()
    }
    pub fn to_vec(&self) -> Vec<f64> {
        self.items.to_vec()
    }
}

impl crate::traits::f64_collection::F64Collection for ImmutableF64ArrayStack {
    fn len(&self) -> usize {
        self.len()
    }
    fn contains(&self, value: f64) -> bool {
        self.contains(value)
    }
    fn iter(&self) -> impl Iterator<Item = f64> + '_ {
        self.iter()
    }
}

impl crate::traits::f64_collection::F64Stack for ImmutableF64ArrayStack {
    fn peek(&self) -> Option<f64> {
        self.peek()
    }
}

impl fmt::Display for ImmutableF64ArrayStack {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "[")?;
        for (i, v) in self.items.iter().enumerate() {
            if i > 0 {
                write!(f, ", ")?;
            }
            write!(f, "{}", v)?;
        }
        write!(f, "]")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_peek_len() {
        let im = ImmutableF64ArrayStack::of(&[1.0f64, 2.0f64]);
        assert_eq!(im.len(), 2);
        assert_eq!(im.peek(), Some(1.0f64));
    }
    #[test]
    fn test_push_immutable() {
        let im = ImmutableF64ArrayStack::of(&[1.0f64]);
        let im2 = im.push(2.0f64);
        assert_eq!(im.len(), 1);
        assert_eq!(im2.len(), 2);
    }
    #[test]
    fn test_pop_immutable() {
        let im = ImmutableF64ArrayStack::of(&[1.0f64, 2.0f64]);
        let (im2, val) = im.pop().unwrap();
        assert_eq!(val, 1.0f64);
        assert_eq!(im2.len(), 1);
        assert_eq!(im.len(), 2);
    }
    #[test]
    fn test_to_mutable() {
        let im = ImmutableF64ArrayStack::of(&[1.0f64]);
        let mut m = im.to_mutable();
        m.push(2.0f64);
        assert_eq!(im.len(), 1);
    }
    #[test]
    fn test_display() {
        assert!(!ImmutableF64ArrayStack::of(&[1.0f64]).to_string().is_empty());
    }
}
