// Code generated by mapdb-codegen. DO NOT EDIT.
use crate::stack::bool_array_stack::BoolArrayStack;
use std::fmt;
use std::sync::Arc;

/// Immutable stack. Push/pop return new stacks (persistent data structure).
#[derive(Debug, Clone)]
pub struct ImmutableBoolArrayStack {
    items: Arc<[bool]>,
}

impl ImmutableBoolArrayStack {
    pub fn from_mutable(stack: &BoolArrayStack) -> Self {
        ImmutableBoolArrayStack {
            items: Arc::from(stack.to_vec().into_boxed_slice()),
        }
    }
    pub fn of(values: &[bool]) -> Self {
        ImmutableBoolArrayStack {
            items: Arc::from(values),
        }
    }
    pub fn peek(&self) -> Option<bool> {
        self.items.first().copied()
    }
    pub fn len(&self) -> usize {
        self.items.len()
    }
    pub fn is_empty(&self) -> bool {
        self.items.is_empty()
    }

    /// Returns (new stack without top, popped value).
    pub fn pop(&self) -> Option<(Self, bool)> {
        if self.items.is_empty() {
            return None;
        }
        let val = self.items[0];
        let rest: Vec<bool> = self.items[1..].to_vec();
        Some((
            ImmutableBoolArrayStack {
                items: Arc::from(rest.into_boxed_slice()),
            },
            val,
        ))
    }

    /// Returns a new stack with the value pushed on top.
    pub fn push(&self, value: bool) -> Self {
        let mut items = vec![value];
        items.extend_from_slice(&self.items);
        ImmutableBoolArrayStack {
            items: Arc::from(items.into_boxed_slice()),
        }
    }

    pub fn to_mutable(&self) -> BoolArrayStack {
        BoolArrayStack::of(&self.items)
    }
    pub fn contains(&self, value: bool) -> bool {
        self.items.contains(&value)
    }
    pub fn iter(&self) -> impl Iterator<Item = bool> + '_ {
        self.items.iter().copied()
    }
    pub fn to_vec(&self) -> Vec<bool> {
        self.items.to_vec()
    }
}

impl crate::traits::bool_collection::BoolCollection for ImmutableBoolArrayStack {
    fn len(&self) -> usize {
        self.len()
    }
    fn contains(&self, value: bool) -> bool {
        self.contains(value)
    }
    fn iter(&self) -> impl Iterator<Item = bool> + '_ {
        self.iter()
    }
}

impl crate::traits::bool_collection::BoolStack for ImmutableBoolArrayStack {
    fn peek(&self) -> Option<bool> {
        self.peek()
    }
}

impl fmt::Display for ImmutableBoolArrayStack {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "[")?;
        for (i, v) in self.items.iter().enumerate() {
            if i > 0 {
                write!(f, ", ")?;
            }
            write!(f, "{}", v)?;
        }
        write!(f, "]")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn test_peek_len() {
        let im = ImmutableBoolArrayStack::of(&[true, false]);
        assert_eq!(im.len(), 2);
        assert_eq!(im.peek(), Some(true));
    }
    #[test]
    fn test_push_immutable() {
        let im = ImmutableBoolArrayStack::of(&[true]);
        let im2 = im.push(false);
        assert_eq!(im.len(), 1);
        assert_eq!(im2.len(), 2);
    }
    #[test]
    fn test_pop_immutable() {
        let im = ImmutableBoolArrayStack::of(&[true, false]);
        let (im2, val) = im.pop().unwrap();
        assert_eq!(val, true);
        assert_eq!(im2.len(), 1);
        assert_eq!(im.len(), 2);
    }
    #[test]
    fn test_to_mutable() {
        let im = ImmutableBoolArrayStack::of(&[true]);
        let mut m = im.to_mutable();
        m.push(false);
        assert_eq!(im.len(), 1);
    }
    #[test]
    fn test_display() {
        assert!(!ImmutableBoolArrayStack::of(&[true]).to_string().is_empty());
    }
}
