// Code generated by mapdb-codegen. DO NOT EDIT.

use std::fmt;

/// Immutable pair of (`bool`, `char`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct BoolCharPair {
    one: bool,
    two: char,
}

impl BoolCharPair {
    pub fn new(one: bool, two: char) -> Self {
        BoolCharPair { one, two }
    }
    pub fn one(&self) -> bool {
        self.one
    }
    pub fn two(&self) -> char {
        self.two
    }

    pub fn swap(&self) -> CharBoolPair {
        CharBoolPair::new(self.two, self.one)
    }
}

impl fmt::Display for BoolCharPair {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "({}, {})", self.one, self.two)
    }
}

// Re-export the swapped pair type if it's the same file (self-pair)
use super::char_bool_pair::CharBoolPair;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_one_two() {
        let p = BoolCharPair::new(true, 'b');
        assert_eq!(p.one(), true);
        assert_eq!(p.two(), 'b');
    }

    #[test]
    fn test_equals() {
        let p1 = BoolCharPair::new(true, 'b');
        let p2 = BoolCharPair::new(true, 'b');
        let p3 = BoolCharPair::new(false, 'a');
        assert_eq!(p1, p2);
        assert_ne!(p1, p3);
    }

    #[test]
    fn test_display() {
        let p = BoolCharPair::new(true, 'b');
        assert!(!p.to_string().is_empty());
    }
}
