// Code generated by mapdb-codegen. DO NOT EDIT.

use std::fmt;

/// Immutable pair of (`f32`, `char`).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct F32CharPair {
    one: f32,
    two: char,
}

impl F32CharPair {
    pub fn new(one: f32, two: char) -> Self {
        F32CharPair { one, two }
    }
    pub fn one(&self) -> f32 {
        self.one
    }
    pub fn two(&self) -> char {
        self.two
    }

    pub fn swap(&self) -> CharF32Pair {
        CharF32Pair::new(self.two, self.one)
    }
}

impl fmt::Display for F32CharPair {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "({}, {})", self.one, self.two)
    }
}

// Re-export the swapped pair type if it's the same file (self-pair)
use super::char_f32_pair::CharF32Pair;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_one_two() {
        let p = F32CharPair::new(1.0f32, 'b');
        assert_eq!(p.one(), 1.0f32);
        assert_eq!(p.two(), 'b');
    }

    #[test]
    fn test_equals() {
        let p1 = F32CharPair::new(1.0f32, 'b');
        let p2 = F32CharPair::new(1.0f32, 'b');
        let p3 = F32CharPair::new(2.0f32, 'a');
        assert_eq!(p1, p2);
        assert_ne!(p1, p3);
    }

    #[test]
    fn test_display() {
        let p = F32CharPair::new(1.0f32, 'b');
        assert!(!p.to_string().is_empty());
    }
}
