// Code generated by mapdb-codegen. DO NOT EDIT.

use std::fmt;

/// Compact bit-packed storage for booleans. Each word holds 64 bits.
/// O(1) set/clear/flip/get; cardinality and bit-wise ops are O(n/64).
///
/// Bits outside the explicit `bit_length` are logically 0 but may be
/// present in the last word; invariants are preserved by masking on
/// `cardinality` and `iter_set_bits` so extra trailing bits never leak.
#[derive(Debug, Clone, Default)]
pub struct BitSet {
    words: Vec<u64>,
    /// Logical length in bits (set by `with_bit_length` / `ensure_bit_length`).
    bit_length: usize,
}

const BITS_PER_WORD: usize = 64;

#[inline]
fn word_index(bit: usize) -> usize {
    bit / BITS_PER_WORD
}

#[inline]
fn word_mask(bit: usize) -> u64 {
    1u64 << (bit % BITS_PER_WORD)
}

impl BitSet {
    pub fn new() -> Self {
        BitSet::default()
    }

    /// Creates a BitSet with capacity for at least `n_bits` bits preallocated.
    pub fn with_bit_length(n_bits: usize) -> Self {
        let n_words = (n_bits + BITS_PER_WORD - 1) / BITS_PER_WORD;
        BitSet {
            words: vec![0u64; n_words],
            bit_length: n_bits,
        }
    }

    /// Ensures capacity to store bit `bit`. Sets `bit_length` to `bit+1`
    /// when greater than the current length.
    fn ensure(&mut self, bit: usize) {
        let needed_words = word_index(bit) + 1;
        if self.words.len() < needed_words {
            self.words.resize(needed_words, 0);
        }
        if bit + 1 > self.bit_length {
            self.bit_length = bit + 1;
        }
    }

    /// Sets bit at `index` to 1.
    pub fn set(&mut self, bit: usize) {
        self.ensure(bit);
        self.words[word_index(bit)] |= word_mask(bit);
    }

    /// Sets bit at `index` to 0. No-op for bits past current length.
    pub fn clear_bit(&mut self, bit: usize) {
        if word_index(bit) < self.words.len() {
            self.words[word_index(bit)] &= !word_mask(bit);
        }
    }

    /// Flips bit at `index`.
    pub fn flip(&mut self, bit: usize) {
        self.ensure(bit);
        self.words[word_index(bit)] ^= word_mask(bit);
    }

    /// Returns true if bit at `index` is 1. Out-of-range indices return false.
    pub fn get(&self, bit: usize) -> bool {
        let wi = word_index(bit);
        if wi >= self.words.len() {
            return false;
        }
        (self.words[wi] & word_mask(bit)) != 0
    }

    /// Returns the number of set bits.
    pub fn cardinality(&self) -> usize {
        let last_idx = if self.bit_length == 0 {
            0
        } else {
            word_index(self.bit_length - 1)
        };
        let mut count = 0usize;
        for (i, w) in self.words.iter().enumerate() {
            if i < last_idx {
                count += w.count_ones() as usize;
            } else if i == last_idx {
                let rem = self.bit_length - i * BITS_PER_WORD;
                let mask = if rem == BITS_PER_WORD {
                    !0u64
                } else {
                    (1u64 << rem) - 1
                };
                count += (w & mask).count_ones() as usize;
            }
        }
        count
    }

    /// Current logical bit length.
    pub fn len(&self) -> usize {
        self.bit_length
    }

    /// Returns true if no bits are set.
    pub fn is_empty(&self) -> bool {
        self.cardinality() == 0
    }

    /// Removes all set bits but retains capacity.
    pub fn clear_all(&mut self) {
        for w in self.words.iter_mut() {
            *w = 0;
        }
    }

    /// Returns true if any bit is set in both `self` and `other`.
    pub fn intersects(&self, other: &Self) -> bool {
        let min = self.words.len().min(other.words.len());
        for i in 0..min {
            if (self.words[i] & other.words[i]) != 0 {
                return true;
            }
        }
        false
    }

    /// In-place bitwise AND.
    pub fn and_in_place(&mut self, other: &Self) {
        for i in 0..self.words.len() {
            let w = if i < other.words.len() {
                other.words[i]
            } else {
                0
            };
            self.words[i] &= w;
        }
    }

    /// In-place bitwise OR (extends length/capacity if `other` is longer).
    pub fn or_in_place(&mut self, other: &Self) {
        if other.words.len() > self.words.len() {
            self.words.resize(other.words.len(), 0);
        }
        if other.bit_length > self.bit_length {
            self.bit_length = other.bit_length;
        }
        for i in 0..other.words.len() {
            self.words[i] |= other.words[i];
        }
    }

    /// In-place bitwise XOR.
    pub fn xor_in_place(&mut self, other: &Self) {
        if other.words.len() > self.words.len() {
            self.words.resize(other.words.len(), 0);
        }
        if other.bit_length > self.bit_length {
            self.bit_length = other.bit_length;
        }
        for i in 0..other.words.len() {
            self.words[i] ^= other.words[i];
        }
    }

    /// In-place AND-NOT (clears in `self` any bits set in `other`).
    pub fn and_not_in_place(&mut self, other: &Self) {
        let min = self.words.len().min(other.words.len());
        for i in 0..min {
            self.words[i] &= !other.words[i];
        }
    }

    /// Returns the index of the next set bit at or after `from`, or `None`.
    pub fn next_set_bit(&self, from: usize) -> Option<usize> {
        let mut wi = word_index(from);
        if wi >= self.words.len() {
            return None;
        }
        // Mask off bits below `from` in the starting word.
        let offset = from % BITS_PER_WORD;
        let mut word = self.words[wi] & (!0u64 << offset);
        loop {
            if word != 0 {
                return Some(wi * BITS_PER_WORD + word.trailing_zeros() as usize);
            }
            wi += 1;
            if wi >= self.words.len() {
                return None;
            }
            word = self.words[wi];
        }
    }

    /// Returns the indices of all set bits in ascending order.
    pub fn to_vec(&self) -> Vec<usize> {
        let mut out = Vec::with_capacity(self.cardinality());
        let mut bit = self.next_set_bit(0);
        while let Some(b) = bit {
            out.push(b);
            bit = self.next_set_bit(b + 1);
        }
        out
    }
}

impl PartialEq for BitSet {
    fn eq(&self, other: &Self) -> bool {
        if self.bit_length != other.bit_length {
            return false;
        }
        let n = self.words.len().max(other.words.len());
        for i in 0..n {
            let a = if i < self.words.len() {
                self.words[i]
            } else {
                0
            };
            let b = if i < other.words.len() {
                other.words[i]
            } else {
                0
            };
            if a != b {
                return false;
            }
        }
        true
    }
}

impl fmt::Display for BitSet {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{{")?;
        let bits = self.to_vec();
        for (i, b) in bits.iter().enumerate() {
            if i > 0 {
                write!(f, ", ")?;
            }
            write!(f, "{}", b)?;
        }
        write!(f, "}}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_set_get_clear() {
        let mut b = BitSet::new();
        b.set(0);
        b.set(5);
        b.set(100);
        assert!(b.get(0));
        assert!(b.get(5));
        assert!(b.get(100));
        assert!(!b.get(1));
        b.clear_bit(5);
        assert!(!b.get(5));
    }

    #[test]
    fn test_flip() {
        let mut b = BitSet::new();
        b.flip(3);
        assert!(b.get(3));
        b.flip(3);
        assert!(!b.get(3));
    }

    #[test]
    fn test_cardinality() {
        let mut b = BitSet::new();
        for i in [1usize, 5, 10, 63, 64, 127, 200].iter() {
            b.set(*i);
        }
        assert_eq!(b.cardinality(), 7);
    }

    #[test]
    fn test_intersects_and_or_xor_andnot() {
        let mut a = BitSet::new();
        a.set(1);
        a.set(5);
        a.set(10);
        let mut c = BitSet::new();
        c.set(5);
        c.set(10);
        c.set(20);
        assert!(a.intersects(&c));
        let mut and_ = a.clone();
        and_.and_in_place(&c);
        assert_eq!(and_.to_vec(), vec![5, 10]);
        let mut or_ = a.clone();
        or_.or_in_place(&c);
        assert_eq!(or_.to_vec(), vec![1, 5, 10, 20]);
        let mut xor = a.clone();
        xor.xor_in_place(&c);
        assert_eq!(xor.to_vec(), vec![1, 20]);
        let mut andnot = a.clone();
        andnot.and_not_in_place(&c);
        assert_eq!(andnot.to_vec(), vec![1]);
    }

    #[test]
    fn test_next_set_bit() {
        let mut b = BitSet::new();
        b.set(0);
        b.set(5);
        b.set(100);
        assert_eq!(b.next_set_bit(0), Some(0));
        assert_eq!(b.next_set_bit(1), Some(5));
        assert_eq!(b.next_set_bit(6), Some(100));
        assert_eq!(b.next_set_bit(101), None);
    }

    #[test]
    fn test_with_bit_length() {
        let b = BitSet::with_bit_length(200);
        assert_eq!(b.len(), 200);
        assert_eq!(b.cardinality(), 0);
    }

    #[test]
    fn test_equals_and_display() {
        let mut a = BitSet::new();
        a.set(1);
        a.set(3);
        let mut c = BitSet::new();
        c.set(1);
        c.set(3);
        assert_eq!(a, c);
        assert!(!a.to_string().is_empty());
    }
}
