// Code generated by mapdb-codegen. DO NOT EDIT.

use std::sync::RwLock;

use super::char_array_list::CharArrayList;

/// Thread-safe wrapper around [`CharArrayList`]. Uses an internal `RwLock`
/// so reads may run concurrently while mutations are exclusive. Wrap in
/// `Arc` for sharing between threads. Lock poisoning panics (parity with
/// Go's panic-on-misuse).
#[derive(Debug, Default)]
pub struct SynchronizedCharArrayList {
    inner: RwLock<CharArrayList>,
}

impl SynchronizedCharArrayList {
    pub fn new() -> Self {
        SynchronizedCharArrayList {
            inner: RwLock::new(CharArrayList::new()),
        }
    }

    pub fn of(values: &[char]) -> Self {
        SynchronizedCharArrayList {
            inner: RwLock::new(CharArrayList::of(values)),
        }
    }

    pub fn push(&self, value: char) {
        self.inner.write().unwrap().push(value);
    }

    pub fn push_all(&self, values: &[char]) {
        self.inner.write().unwrap().push_all(values);
    }

    pub fn get(&self, index: usize) -> Option<char> {
        self.inner.read().unwrap().get(index)
    }

    pub fn set(&self, index: usize, value: char) -> char {
        self.inner.write().unwrap().set(index, value)
    }

    pub fn remove_at_index(&self, index: usize) -> char {
        self.inner.write().unwrap().remove_at_index(index)
    }

    pub fn remove(&self, value: char) -> bool {
        self.inner.write().unwrap().remove(value)
    }

    pub fn contains(&self, value: char) -> bool {
        self.inner.read().unwrap().contains(value)
    }

    pub fn len(&self) -> usize {
        self.inner.read().unwrap().len()
    }
    pub fn is_empty(&self) -> bool {
        self.inner.read().unwrap().is_empty()
    }

    pub fn clear(&self) {
        self.inner.write().unwrap().clear();
    }

    /// Returns an owned snapshot for iteration.
    pub fn to_vec(&self) -> Vec<char> {
        self.inner.read().unwrap().to_vec()
    }

    /// Iterates under the read lock. The closure must not re-enter the
    /// wrapper or a deadlock will result.
    pub fn for_each(&self, f: impl FnMut(char)) {
        self.inner.read().unwrap().for_each(f);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;
    use std::thread;

    #[test]
    fn test_basic_ops() {
        let l = SynchronizedCharArrayList::new();
        assert!(l.is_empty());
        l.push('a');
        l.push('b');
        l.push('c');
        assert_eq!(l.len(), 3);
        assert_eq!(l.get(0), Some('a'));
        assert!(l.contains('b'));
        let old = l.set(0, 'c');
        assert_eq!(old, 'a');
        let removed = l.remove_at_index(0);
        assert_eq!(removed, 'c');
        assert_eq!(l.len(), 2);
        l.clear();
        assert!(l.is_empty());
    }

    #[test]
    fn test_to_vec_and_for_each() {
        let l = SynchronizedCharArrayList::of(&['a', 'b', 'c']);
        let snap = l.to_vec();
        assert_eq!(snap.len(), 3);
        let mut count = 0usize;
        l.for_each(|_| count += 1);
        assert_eq!(count, 3);
    }

    #[test]
    fn test_concurrent() {
        let l = Arc::new(SynchronizedCharArrayList::new());
        let mut handles = Vec::new();
        for _ in 0..4 {
            let c = Arc::clone(&l);
            handles.push(thread::spawn(move || {
                for _ in 0..100 {
                    c.push('a');
                }
            }));
        }
        for h in handles {
            h.join().unwrap();
        }
        assert_eq!(l.len(), 400);
    }
}
