// Code generated by mapdb-codegen. DO NOT EDIT.

use crate::hash_table::OpenHashMap;
use std::fmt;

/// Bag (multiset) of `f32` values with occurrence counting.
/// Uses custom open-addressing hash table internally.
#[derive(Debug, Clone)]
pub struct F32HashBag {
    counts: OpenHashMap<f32, usize>,
    size: usize,
}

impl F32HashBag {
    pub fn new() -> Self {
        F32HashBag {
            counts: OpenHashMap::new(),
            size: 0,
        }
    }

    pub fn of(values: &[f32]) -> Self {
        let mut b = Self::new();
        for &v in values {
            b.add(v);
        }
        b
    }

    pub fn add(&mut self, value: f32) {
        if let Some(count) = self.counts.get_mut(value) {
            *count += 1;
        } else {
            self.counts.insert(value, 1);
        }
        self.size += 1;
    }

    /// Removes one occurrence. Returns true if the value was present.
    pub fn remove(&mut self, value: f32) -> bool {
        if let Some(count) = self.counts.get_mut(value) {
            *count -= 1;
            if *count == 0 {
                self.counts.remove(value);
            }
            self.size -= 1;
            true
        } else {
            false
        }
    }

    /// Removes all occurrences of the value.
    pub fn remove_all(&mut self, value: f32) -> bool {
        if let Some(count) = self.counts.remove(value) {
            self.size -= count;
            true
        } else {
            false
        }
    }

    pub fn occurrences_of(&self, value: f32) -> usize {
        self.counts.get(value).unwrap_or(0)
    }

    pub fn contains(&self, value: f32) -> bool {
        self.occurrences_of(value) > 0
    }
    pub fn size(&self) -> usize {
        self.size
    }
    pub fn size_distinct(&self) -> usize {
        self.counts.len()
    }
    pub fn is_empty(&self) -> bool {
        self.size == 0
    }

    pub fn clear(&mut self) {
        self.counts.clear();
        self.size = 0;
    }

    /// Ensures the internal count-map can hold `additional` more distinct
    /// values without triggering a rehash. Returns `TryReserveError` on
    /// allocator failure. Note that the count is bounded by distinct
    /// values, not total occurrences. See `docs/rust/error-handling.md`.
    pub fn try_reserve(
        &mut self,
        additional: usize,
    ) -> Result<(), std::collections::TryReserveError> {
        self.counts.try_reserve(additional)
    }

    /// Iterates over all elements, repeating each value by its count.
    pub fn iter(&self) -> impl Iterator<Item = f32> + '_ {
        self.counts
            .iter()
            .flat_map(|(k, c)| std::iter::repeat_n(k, c))
    }

    /// Iterates over distinct values.
    pub fn iter_distinct(&self) -> impl Iterator<Item = f32> + '_ {
        self.counts.iter().map(|(k, _)| k)
    }

    pub fn for_each_with_occurrences(&self, mut f: impl FnMut(f32, usize)) {
        for (v, c) in self.counts.iter() {
            f(v, c);
        }
    }

    pub fn select(&self, predicate: impl Fn(f32) -> bool) -> Self {
        let mut result = Self::new();
        self.for_each_with_occurrences(|v, c| {
            if predicate(v) {
                for _ in 0..c {
                    result.add(v);
                }
            }
        });
        result
    }

    pub fn to_vec(&self) -> Vec<f32> {
        let mut result = Vec::with_capacity(self.size);
        self.for_each_with_occurrences(|v, c| {
            for _ in 0..c {
                result.push(v);
            }
        });
        result
    }
}

impl Default for F32HashBag {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for F32HashBag {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{{")?;
        let mut first = true;
        self.for_each_with_occurrences(|v, c| {
            if !first {
                let _ = write!(f, ", ");
            }
            let _ = write!(f, "{}x{}", v, c);
            first = false;
        });
        write!(f, "}}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_add_occurrences() {
        let mut b = F32HashBag::new();
        b.add(1.0f32);
        b.add(1.0f32);
        b.add(2.0f32);
        assert_eq!(b.occurrences_of(1.0f32), 2);
        assert_eq!(b.occurrences_of(2.0f32), 1);
        assert_eq!(b.size(), 3);
        assert_eq!(b.size_distinct(), 2);
    }

    #[test]
    fn test_remove() {
        let mut b = F32HashBag::of(&[1.0f32, 1.0f32, 1.0f32]);
        assert!(b.remove(1.0f32));
        assert_eq!(b.occurrences_of(1.0f32), 2);
    }

    #[test]
    fn test_remove_all() {
        let mut b = F32HashBag::of(&[1.0f32, 1.0f32, 2.0f32]);
        assert!(b.remove_all(1.0f32));
        assert!(!b.contains(1.0f32));
        assert_eq!(b.size(), 1);
    }

    #[test]
    fn test_clear() {
        let mut b = F32HashBag::of(&[1.0f32]);
        b.clear();
        assert!(b.is_empty());
    }

    #[test]
    fn test_for_each_with_occurrences() {
        let b = F32HashBag::of(&[1.0f32, 1.0f32, 2.0f32]);
        let mut total = 0;
        b.for_each_with_occurrences(|_, c| total += c);
        assert_eq!(total, 3);
    }

    #[test]
    fn test_select() {
        let b = F32HashBag::of(&[1.0f32, 2.0f32, 3.0f32]);
        assert_eq!(b.select(|v| v > 1.0f32).size(), 2);
    }

    #[test]
    fn test_display() {
        let b = F32HashBag::of(&[1.0f32]);
        assert!(!b.to_string().is_empty());
    }

    #[test]
    fn test_try_reserve_happy_path() {
        let mut b = F32HashBag::new();
        b.try_reserve(100).unwrap();
    }

    #[test]
    fn test_try_reserve_propagates_capacity_overflow() {
        let mut b = F32HashBag::new();
        assert!(b.try_reserve(usize::MAX / 2).is_err());
    }
}

impl crate::traits::f32_collection::F32Collection for F32HashBag {
    fn len(&self) -> usize {
        self.size()
    }
    fn contains(&self, value: f32) -> bool {
        self.contains(value)
    }
    fn iter(&self) -> impl Iterator<Item = f32> + '_ {
        self.iter()
    }
}

impl crate::traits::f32_collection::F32MutableCollection for F32HashBag {
    fn clear(&mut self) {
        self.clear()
    }
}

impl crate::traits::f32_collection::F32Bag for F32HashBag {
    fn occurrences_of(&self, value: f32) -> usize {
        self.occurrences_of(value)
    }
    fn size_distinct(&self) -> usize {
        self.size_distinct()
    }
}

impl crate::traits::f32_collection::F32MutableBag for F32HashBag {
    fn add(&mut self, value: f32) {
        self.add(value)
    }
}
