// Code generated by mapdb-codegen. DO NOT EDIT.

use std::collections::BTreeMap;
use std::fmt;

/// Sorted bag (multiset) of `i16` values with occurrence counting.
/// Elements are kept in sorted order via BTreeMap.
#[derive(Debug, Clone)]
pub struct I16TreeBag {
    counts: BTreeMap<i16, usize>,
    size: usize,
}

impl I16TreeBag {
    pub fn new() -> Self {
        I16TreeBag {
            counts: BTreeMap::new(),
            size: 0,
        }
    }

    pub fn of(values: &[i16]) -> Self {
        let mut b = Self::new();
        for &v in values {
            b.add(v);
        }
        b
    }

    pub fn add(&mut self, value: i16) {
        *self.counts.entry(value).or_insert(0) += 1;
        self.size += 1;
    }

    /// Removes one occurrence. Returns true if the value was present.
    pub fn remove(&mut self, value: i16) -> bool {
        let k = value;
        if let Some(count) = self.counts.get_mut(&k) {
            *count -= 1;
            if *count == 0 {
                self.counts.remove(&k);
            }
            self.size -= 1;
            true
        } else {
            false
        }
    }

    /// Removes all occurrences. Returns true if present.
    pub fn remove_all(&mut self, value: i16) -> bool {
        let k = value;
        if let Some(count) = self.counts.remove(&k) {
            self.size -= count;
            true
        } else {
            false
        }
    }

    pub fn occurrences_of(&self, value: i16) -> usize {
        self.counts.get(&(value)).copied().unwrap_or(0)
    }

    pub fn contains(&self, value: i16) -> bool {
        self.occurrences_of(value) > 0
    }
    pub fn size(&self) -> usize {
        self.size
    }
    pub fn size_distinct(&self) -> usize {
        self.counts.len()
    }
    pub fn is_empty(&self) -> bool {
        self.size == 0
    }

    pub fn clear(&mut self) {
        self.counts.clear();
        self.size = 0;
    }

    /// No-op reservation hook. `BTreeMap` grows node-by-node and does
    /// not expose a fallible pre-reservation API; this method exists for
    /// API uniformity with the hash-backed bags and always returns
    /// `Ok(())`. Callers who need opt-in OOM handling should prefer the
    /// hash-backed `Bag` primitives. See `docs/rust/error-handling.md`.
    pub fn try_reserve(
        &mut self,
        additional: usize,
    ) -> Result<(), std::collections::TryReserveError> {
        let _ = additional;
        Ok(())
    }

    /// Returns the minimum element, or None.
    pub fn min(&self) -> Option<i16> {
        self.counts.keys().next().copied()
    }

    /// Returns the maximum element, or None.
    pub fn max(&self) -> Option<i16> {
        self.counts.keys().next_back().copied()
    }

    /// Iterates over all elements in sorted order, repeating each value by its count.
    pub fn iter(&self) -> impl Iterator<Item = i16> + '_ {
        self.counts
            .iter()
            .flat_map(|(&k, &c)| std::iter::repeat_n(k, c))
    }

    /// Iterates over distinct values in sorted order.
    pub fn iter_distinct(&self) -> impl Iterator<Item = i16> + '_ {
        self.counts.keys().copied()
    }

    pub fn for_each_with_occurrences(&self, mut f: impl FnMut(i16, usize)) {
        for (&k, &c) in &self.counts {
            f(k, c);
        }
    }

    pub fn select(&self, predicate: impl Fn(i16) -> bool) -> Self {
        let mut result = Self::new();
        self.for_each_with_occurrences(|v, c| {
            if predicate(v) {
                for _ in 0..c {
                    result.add(v);
                }
            }
        });
        result
    }

    pub fn to_vec(&self) -> Vec<i16> {
        let mut result = Vec::with_capacity(self.size);
        self.for_each_with_occurrences(|v, c| {
            for _ in 0..c {
                result.push(v);
            }
        });
        result
    }

    /// Returns elements as a sorted slice (each element repeated per count).
    pub fn to_sorted_vec(&self) -> Vec<i16> {
        self.to_vec() // already sorted since BTreeMap iterates in order
    }
}

impl Default for I16TreeBag {
    fn default() -> Self {
        Self::new()
    }
}

impl fmt::Display for I16TreeBag {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{{")?;
        let mut first = true;
        self.for_each_with_occurrences(|v, c| {
            if !first {
                let _ = write!(f, ", ");
            }
            let _ = write!(f, "{}x{}", v, c);
            first = false;
        });
        write!(f, "}}")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_add_occurrences() {
        let mut b = I16TreeBag::new();
        b.add(1);
        b.add(1);
        b.add(2);
        assert_eq!(b.occurrences_of(1), 2);
        assert_eq!(b.occurrences_of(2), 1);
        assert_eq!(b.size(), 3);
        assert_eq!(b.size_distinct(), 2);
    }

    #[test]
    fn test_remove() {
        let mut b = I16TreeBag::of(&[1, 1, 1]);
        assert!(b.remove(1));
        assert_eq!(b.occurrences_of(1), 2);
    }

    #[test]
    fn test_remove_all() {
        let mut b = I16TreeBag::of(&[1, 1, 2]);
        assert!(b.remove_all(1));
        assert!(!b.contains(1));
        assert_eq!(b.size(), 1);
    }

    #[test]
    fn test_sorted_iteration() {
        let b = I16TreeBag::of(&[3, 1, 2]);
        let items = b.to_sorted_vec();
        assert_eq!(items[0], 1);
        assert_eq!(items[items.len() - 1], 3);
    }

    #[test]
    fn test_min_max() {
        let b = I16TreeBag::of(&[3, 1, 2]);
        assert_eq!(b.min(), Some(1));
        assert_eq!(b.max(), Some(3));
    }

    #[test]
    fn test_clear() {
        let mut b = I16TreeBag::of(&[1]);
        b.clear();
        assert!(b.is_empty());
    }

    #[test]
    fn test_display() {
        let b = I16TreeBag::of(&[1]);
        assert!(!b.to_string().is_empty());
    }

    #[test]
    fn test_try_reserve_is_noop_happy_path() {
        let mut b = I16TreeBag::new();
        b.try_reserve(100).unwrap();
        b.try_reserve(usize::MAX / 2).unwrap(); // no-op, never fails
    }
}

impl crate::traits::i16_collection::I16Collection for I16TreeBag {
    fn len(&self) -> usize {
        self.size()
    }
    fn contains(&self, value: i16) -> bool {
        self.contains(value)
    }
    fn iter(&self) -> impl Iterator<Item = i16> + '_ {
        self.iter()
    }
}

impl crate::traits::i16_collection::I16MutableCollection for I16TreeBag {
    fn clear(&mut self) {
        self.clear()
    }
}

impl crate::traits::i16_collection::I16Bag for I16TreeBag {
    fn occurrences_of(&self, value: i16) -> usize {
        self.occurrences_of(value)
    }
    fn size_distinct(&self) -> usize {
        self.size_distinct()
    }
}

impl crate::traits::i16_collection::I16MutableBag for I16TreeBag {
    fn add(&mut self, value: i16) {
        self.add(value)
    }
}
