// Code generated by mapdb-codegen. DO NOT EDIT.

pub mod bool_hash_bag;
pub mod bool_tree_bag;
pub mod char_hash_bag;
pub mod char_tree_bag;
pub mod f32_hash_bag;
pub mod f32_tree_bag;
pub mod f64_hash_bag;
pub mod f64_tree_bag;
pub mod i16_hash_bag;
pub mod i16_tree_bag;
pub mod i32_hash_bag;
pub mod i32_tree_bag;
pub mod i64_hash_bag;
pub mod i64_tree_bag;
pub mod i8_hash_bag;
pub mod i8_tree_bag;
pub mod synchronized_bool_hash_bag;
pub mod synchronized_char_hash_bag;
pub mod synchronized_f32_hash_bag;
pub mod synchronized_f64_hash_bag;
pub mod synchronized_i16_hash_bag;
pub mod synchronized_i32_hash_bag;
pub mod synchronized_i64_hash_bag;
pub mod synchronized_i8_hash_bag;
