// Code generated by mapdb-codegen. DO NOT EDIT.

use std::sync::RwLock;

use super::char_hash_bag::CharHashBag;

/// Thread-safe wrapper around [`CharHashBag`].
#[derive(Debug, Default)]
pub struct SynchronizedCharHashBag {
    inner: RwLock<CharHashBag>,
}

impl SynchronizedCharHashBag {
    pub fn new() -> Self {
        SynchronizedCharHashBag {
            inner: RwLock::new(CharHashBag::new()),
        }
    }

    pub fn of(values: &[char]) -> Self {
        SynchronizedCharHashBag {
            inner: RwLock::new(CharHashBag::of(values)),
        }
    }

    pub fn add(&self, value: char) {
        self.inner.write().unwrap().add(value);
    }

    pub fn remove(&self, value: char) -> bool {
        self.inner.write().unwrap().remove(value)
    }

    pub fn remove_all(&self, value: char) -> bool {
        self.inner.write().unwrap().remove_all(value)
    }

    pub fn occurrences_of(&self, value: char) -> usize {
        self.inner.read().unwrap().occurrences_of(value)
    }

    pub fn contains(&self, value: char) -> bool {
        self.inner.read().unwrap().contains(value)
    }

    pub fn size(&self) -> usize {
        self.inner.read().unwrap().size()
    }
    pub fn size_distinct(&self) -> usize {
        self.inner.read().unwrap().size_distinct()
    }
    pub fn is_empty(&self) -> bool {
        self.inner.read().unwrap().is_empty()
    }
    pub fn clear(&self) {
        self.inner.write().unwrap().clear();
    }

    pub fn to_vec(&self) -> Vec<char> {
        self.inner.read().unwrap().to_vec()
    }

    pub fn for_each(&self, mut f: impl FnMut(char)) {
        let snap = self.inner.read().unwrap().to_vec();
        for v in snap {
            f(v);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;
    use std::thread;

    #[test]
    fn test_basic_ops() {
        let b = SynchronizedCharHashBag::new();
        assert!(b.is_empty());
        b.add('a');
        b.add('a');
        b.add('b');
        assert_eq!(b.size(), 3);
        assert_eq!(b.occurrences_of('a'), 2);
        assert!(b.contains('a'));
        assert!(b.remove('a'));
        assert_eq!(b.occurrences_of('a'), 1);
        b.clear();
        assert!(b.is_empty());
    }

    #[test]
    fn test_to_vec_and_for_each() {
        let b = SynchronizedCharHashBag::new();
        b.add('a');
        b.add('b');
        assert_eq!(b.to_vec().len(), 2);
        let mut count = 0usize;
        b.for_each(|_| count += 1);
        assert_eq!(count, 2);
    }

    #[test]
    fn test_concurrent() {
        let b = Arc::new(SynchronizedCharHashBag::new());
        let mut handles = Vec::new();
        for _ in 0..4 {
            let c = Arc::clone(&b);
            handles.push(thread::spawn(move || {
                for _ in 0..100 {
                    c.add('a');
                }
            }));
        }
        for h in handles {
            h.join().unwrap();
        }
        assert_eq!(b.size(), 400);
        assert_eq!(b.occurrences_of('a'), 400);
    }
}
