// Code generated by mapdb-codegen. DO NOT EDIT.

/// Read-only trait for any collection of `i64` values.
///
/// Implementors provide three required methods — [`len`], [`contains`],
/// and [`iter`] — and get a rich set of defaulted query methods for free,
/// following the same pattern as Rust's [`Iterator`] trait.
pub trait I64Collection {
    // ── Required methods ────────────────────────────────────────────

    /// Returns the number of elements.
    fn len(&self) -> usize;

    /// Returns true if the collection contains the value.
    fn contains(&self, value: i64) -> bool;

    /// Returns an iterator over the elements.
    fn iter(&self) -> impl Iterator<Item = i64> + '_;

    // ── Defaulted methods ───────────────────────────────────────────

    /// Returns true if the collection is empty.
    fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// Returns all elements as a Vec.
    fn to_vec(&self) -> Vec<i64> {
        self.iter().collect()
    }

    /// Calls the given function for each element.
    fn for_each(&self, mut f: impl FnMut(i64)) {
        for v in self.iter() {
            f(v);
        }
    }

    /// Returns true if any element satisfies the predicate.
    fn any_satisfy(&self, predicate: impl Fn(i64) -> bool) -> bool {
        self.iter().any(predicate)
    }

    /// Returns true if all elements satisfy the predicate.
    fn all_satisfy(&self, predicate: impl Fn(i64) -> bool) -> bool {
        self.iter().all(predicate)
    }

    /// Returns true if no element satisfies the predicate.
    fn none_satisfy(&self, predicate: impl Fn(i64) -> bool) -> bool {
        !self.iter().any(predicate)
    }

    /// Returns the count of elements satisfying the predicate.
    fn count_where(&self, predicate: impl Fn(i64) -> bool) -> usize {
        self.iter().filter(|&v| predicate(v)).count()
    }

    /// Returns the first element satisfying the predicate, or None.
    fn detect(&self, predicate: impl Fn(i64) -> bool) -> Option<i64> {
        self.iter().find(|&v| predicate(v))
    }

    /// Returns the minimum element, or None if empty.
    fn min_value(&self) -> Option<i64> {
        self.iter().min()
    }

    /// Returns the maximum element, or None if empty.
    fn max_value(&self) -> Option<i64> {
        self.iter().max()
    }

    /// Returns elements satisfying the predicate as a Vec.
    fn select(&self, predicate: impl Fn(i64) -> bool) -> Vec<i64> {
        self.iter().filter(|&v| predicate(v)).collect()
    }

    /// Returns elements NOT satisfying the predicate as a Vec.
    fn reject(&self, predicate: impl Fn(i64) -> bool) -> Vec<i64> {
        self.iter().filter(|&v| !predicate(v)).collect()
    }

    /// Folds all elements using the given function and initial value.
    fn inject_into<R>(&self, initial: R, mut f: impl FnMut(R, i64) -> R) -> R {
        let mut acc = initial;
        for v in self.iter() {
            acc = f(acc, v);
        }
        acc
    }

    /// Returns the sum of all elements.
    fn sum(&self) -> i64 {
        self.iter().sum()
    }
}

/// Mutable collection trait extending I64Collection.
pub trait I64MutableCollection: I64Collection {
    /// Removes all elements.
    fn clear(&mut self);
}

// ── Category traits — mirror Java's IntList / IntSet / IntBag / IntStack ──
//
// These distinguish *what kind of collection* is required without naming a
// concrete type. `fn process_list<L: I64List>(l: &L)` accepts ArrayList and
// ImmutableArrayList but not HashSet.

/// Read-only ordered list of `i64` values with positional access.
pub trait I64List: I64Collection {
    /// Returns the element at `index`, or None if out of bounds.
    fn get(&self, index: usize) -> Option<i64>;

    /// Returns the index of the first occurrence of `value`, or None if not found.
    fn index_of(&self, value: i64) -> Option<usize>;
}

/// Mutable ordered list extending I64List + I64MutableCollection.
pub trait I64MutableList: I64List + I64MutableCollection {
    /// Appends a value to the end of the list.
    fn push(&mut self, value: i64);
    /// Replaces the element at `index`. Returns the previous value.
    fn set(&mut self, index: usize, value: i64) -> i64;
}

/// Read-only set of `i64` values (no positional access; uniqueness implied).
pub trait I64Set: I64Collection {}

/// Mutable set extending I64Set + I64MutableCollection.
pub trait I64MutableSet: I64Set + I64MutableCollection {
    /// Inserts a value. Returns true if the value was not already present.
    fn add(&mut self, value: i64) -> bool;
}

/// Read-only multiset (bag) of `i64` values with occurrence counts.
pub trait I64Bag: I64Collection {
    /// Returns the number of times `value` occurs in the bag.
    fn occurrences_of(&self, value: i64) -> usize;
    /// Returns the number of *distinct* values (ignoring multiplicity).
    fn size_distinct(&self) -> usize;
}

/// Mutable bag extending I64Bag + I64MutableCollection.
pub trait I64MutableBag: I64Bag + I64MutableCollection {
    /// Adds one occurrence of `value`.
    fn add(&mut self, value: i64);
}

/// Read-only LIFO stack of `i64` values.
pub trait I64Stack: I64Collection {
    /// Returns the top of the stack without removing it.
    fn peek(&self) -> Option<i64>;
}

/// Mutable LIFO stack extending I64Stack + I64MutableCollection.
pub trait I64MutableStack: I64Stack + I64MutableCollection {
    /// Pushes a value onto the top of the stack.
    fn push(&mut self, value: i64);
    /// Pops and returns the top of the stack, or None if empty.
    fn pop(&mut self) -> Option<i64>;
}

#[cfg(test)]
mod verify {
    use super::*;
    fn _assert_collection<T: I64Collection>() {}
    fn _assert_mutable<T: I64MutableCollection>() {}
    fn _assert_list<T: I64List>() {}
    fn _assert_mutable_list<T: I64MutableList>() {}
    fn _assert_set<T: I64Set>() {}
    fn _assert_mutable_set<T: I64MutableSet>() {}
    fn _assert_bag<T: I64Bag>() {}
    fn _assert_mutable_bag<T: I64MutableBag>() {}
    fn _assert_stack<T: I64Stack>() {}
    fn _assert_mutable_stack<T: I64MutableStack>() {}

    /// Compile-time verification that every concrete collection type for
    /// `i64` implements the appropriate read-only and mutable traits.
    /// If any implementation is missing this test fails to compile.
    #[test]
    fn types_implement_traits() {
        // Mutable collections — base Collection / MutableCollection trait
        _assert_collection::<crate::arraylist::i64_array_list::I64ArrayList>();
        _assert_mutable::<crate::arraylist::i64_array_list::I64ArrayList>();
        _assert_collection::<crate::hashset::i64_hash_set::I64HashSet>();
        _assert_mutable::<crate::hashset::i64_hash_set::I64HashSet>();
        _assert_collection::<crate::bag::i64_hash_bag::I64HashBag>();
        _assert_mutable::<crate::bag::i64_hash_bag::I64HashBag>();
        _assert_collection::<crate::bag::i64_tree_bag::I64TreeBag>();
        _assert_mutable::<crate::bag::i64_tree_bag::I64TreeBag>();
        _assert_collection::<crate::stack::i64_array_stack::I64ArrayStack>();
        _assert_mutable::<crate::stack::i64_array_stack::I64ArrayStack>();
        _assert_collection::<crate::treeset::i64_tree_set::I64TreeSet>();
        _assert_mutable::<crate::treeset::i64_tree_set::I64TreeSet>();

        // Immutable collections — read-only trait only
        _assert_collection::<crate::immutable::immutable_i64_array_list::ImmutableI64ArrayList>();
        _assert_collection::<crate::immutable::immutable_i64_hash_set::ImmutableI64HashSet>();
        _assert_collection::<crate::immutable::immutable_i64_hash_bag::ImmutableI64HashBag>();
        _assert_collection::<crate::immutable::immutable_i64_array_stack::ImmutableI64ArrayStack>();

        // Category traits — Lists
        _assert_list::<crate::arraylist::i64_array_list::I64ArrayList>();
        _assert_mutable_list::<crate::arraylist::i64_array_list::I64ArrayList>();
        _assert_list::<crate::immutable::immutable_i64_array_list::ImmutableI64ArrayList>();

        // Category traits — Sets
        _assert_set::<crate::hashset::i64_hash_set::I64HashSet>();
        _assert_mutable_set::<crate::hashset::i64_hash_set::I64HashSet>();
        _assert_set::<crate::treeset::i64_tree_set::I64TreeSet>();
        _assert_mutable_set::<crate::treeset::i64_tree_set::I64TreeSet>();
        _assert_set::<crate::immutable::immutable_i64_hash_set::ImmutableI64HashSet>();

        // Category traits — Bags
        _assert_bag::<crate::bag::i64_hash_bag::I64HashBag>();
        _assert_mutable_bag::<crate::bag::i64_hash_bag::I64HashBag>();
        _assert_bag::<crate::bag::i64_tree_bag::I64TreeBag>();
        _assert_mutable_bag::<crate::bag::i64_tree_bag::I64TreeBag>();
        _assert_bag::<crate::immutable::immutable_i64_hash_bag::ImmutableI64HashBag>();

        // Category traits — Stacks
        _assert_stack::<crate::stack::i64_array_stack::I64ArrayStack>();
        _assert_mutable_stack::<crate::stack::i64_array_stack::I64ArrayStack>();
        _assert_stack::<crate::immutable::immutable_i64_array_stack::ImmutableI64ArrayStack>();

        // Interval — read-only Collection (integer types only)
        _assert_collection::<crate::interval::i64_interval::I64Interval>();
    }

    /// Proves the trait contract is reachable from outside the codegen.
    /// A minimal third-party type implementing I64MutableList, with no
    /// dependency on generated code beyond the trait definitions.
    struct FakeI64List {
        items: Vec<i64>,
    }

    impl I64Collection for FakeI64List {
        fn len(&self) -> usize {
            self.items.len()
        }
        fn contains(&self, value: i64) -> bool {
            self.items.contains(&value)
        }
        fn iter(&self) -> impl Iterator<Item = i64> + '_ {
            self.items.iter().copied()
        }
    }
    impl I64MutableCollection for FakeI64List {
        fn clear(&mut self) {
            self.items.clear();
        }
    }
    impl I64List for FakeI64List {
        fn get(&self, index: usize) -> Option<i64> {
            self.items.get(index).copied()
        }
        fn index_of(&self, value: i64) -> Option<usize> {
            self.items.iter().position(|&v| v == value)
        }
    }
    impl I64MutableList for FakeI64List {
        fn push(&mut self, value: i64) {
            self.items.push(value);
        }
        fn set(&mut self, index: usize, value: i64) -> i64 {
            let old = self.items[index];
            self.items[index] = value;
            old
        }
    }

    #[test]
    fn third_party_impl_satisfies_traits() {
        _assert_mutable_list::<FakeI64List>();
        let mut fake = FakeI64List { items: Vec::new() };
        fake.push(1);
        assert_eq!(fake.len(), 1);
        assert!(fake.contains(1));
        // Verify defaulted methods work via trait dispatch
        assert!(!fake.is_empty());
        assert_eq!(fake.to_vec().len(), 1);
    }
}
