// Code generated by mapdb-codegen. DO NOT EDIT.

//! Newtype wrappers for f32/f64 that implement Hash + Eq via bit representation.
//! Used as hash map keys where the standard f32/f64 cannot be used directly.

use std::hash::{Hash, Hasher};

/// Wrapper for f32 that implements Hash and Eq via to_bits().
/// NaN values with the same bit pattern are considered equal.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct HashableF32(pub f32);

impl Eq for HashableF32 {}

impl Hash for HashableF32 {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.0.to_bits().hash(state);
    }
}

impl PartialOrd for HashableF32 {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for HashableF32 {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.0.total_cmp(&other.0)
    }
}

impl std::fmt::Display for HashableF32 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl From<f32> for HashableF32 {
    fn from(v: f32) -> Self {
        HashableF32(v)
    }
}

/// Wrapper for f64 that implements Hash and Eq via to_bits().
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct HashableF64(pub f64);

impl Eq for HashableF64 {}

impl Hash for HashableF64 {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.0.to_bits().hash(state);
    }
}

impl PartialOrd for HashableF64 {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for HashableF64 {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.0.total_cmp(&other.0)
    }
}

impl std::fmt::Display for HashableF64 {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl From<f64> for HashableF64 {
    fn from(v: f64) -> Self {
        HashableF64(v)
    }
}
