// Code generated by mapdb-codegen. DO NOT EDIT.

pub mod bool_array_stack;
pub mod char_array_stack;
pub mod f32_array_stack;
pub mod f64_array_stack;
pub mod i16_array_stack;
pub mod i32_array_stack;
pub mod i64_array_stack;
pub mod i8_array_stack;
pub mod synchronized_bool_array_stack;
pub mod synchronized_char_array_stack;
pub mod synchronized_f32_array_stack;
pub mod synchronized_f64_array_stack;
pub mod synchronized_i16_array_stack;
pub mod synchronized_i32_array_stack;
pub mod synchronized_i64_array_stack;
pub mod synchronized_i8_array_stack;
