// Code generated by mapdb-codegen. DO NOT EDIT.

use std::sync::RwLock;

use super::f32_array_stack::F32ArrayStack;

/// Thread-safe wrapper around [`F32ArrayStack`].
#[derive(Debug, Default)]
pub struct SynchronizedF32ArrayStack {
    inner: RwLock<F32ArrayStack>,
}

impl SynchronizedF32ArrayStack {
    pub fn new() -> Self {
        SynchronizedF32ArrayStack {
            inner: RwLock::new(F32ArrayStack::new()),
        }
    }

    pub fn of(values: &[f32]) -> Self {
        SynchronizedF32ArrayStack {
            inner: RwLock::new(F32ArrayStack::of(values)),
        }
    }

    pub fn push(&self, value: f32) {
        self.inner.write().unwrap().push(value);
    }

    pub fn pop(&self) -> Option<f32> {
        self.inner.write().unwrap().pop()
    }

    pub fn peek(&self) -> Option<f32> {
        self.inner.read().unwrap().peek()
    }

    pub fn contains(&self, value: f32) -> bool {
        self.inner.read().unwrap().contains(value)
    }

    pub fn len(&self) -> usize {
        self.inner.read().unwrap().len()
    }
    pub fn is_empty(&self) -> bool {
        self.inner.read().unwrap().is_empty()
    }
    pub fn clear(&self) {
        self.inner.write().unwrap().clear();
    }

    pub fn to_vec(&self) -> Vec<f32> {
        self.inner.read().unwrap().to_vec()
    }

    pub fn for_each(&self, f: impl FnMut(f32)) {
        self.inner.read().unwrap().for_each(f);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;
    use std::thread;

    #[test]
    fn test_basic_ops() {
        let s = SynchronizedF32ArrayStack::new();
        assert!(s.is_empty());
        s.push(1.0f32);
        s.push(2.0f32);
        assert_eq!(s.len(), 2);
        assert_eq!(s.peek(), Some(2.0f32));
        assert_eq!(s.pop(), Some(2.0f32));
        assert_eq!(s.len(), 1);
        assert!(s.contains(1.0f32));
        s.clear();
        assert!(s.is_empty());
    }

    #[test]
    fn test_to_vec_and_for_each() {
        let s = SynchronizedF32ArrayStack::of(&[1.0f32, 2.0f32, 3.0f32]);
        assert_eq!(s.to_vec().len(), 3);
        let mut count = 0usize;
        s.for_each(|_| count += 1);
        assert_eq!(count, 3);
    }

    #[test]
    fn test_concurrent() {
        let s = Arc::new(SynchronizedF32ArrayStack::new());
        let mut handles = Vec::new();
        for _ in 0..4 {
            let c = Arc::clone(&s);
            handles.push(thread::spawn(move || {
                for _ in 0..100 {
                    c.push(1.0f32);
                }
            }));
        }
        for h in handles {
            h.join().unwrap();
        }
        assert_eq!(s.len(), 400);
    }
}
